### ISSUE TITLE
Possible to have custom validators on reform objects?

### ISSUE THREAD

**Issue by EverybodyKurts** [apotonick/reform#118]
I read through the readme but there weren't any examples of custom validators on form objects. I just wanted to double check that it's possible to for reform objects to contain and perform custom validators.

Thank you!

Kurt

**Comment by AnwarShah** [comment]
@apotonick  is it still possible? The github page shows error 404. Also if possible, how can i copy the error messages?

**Comment by apotonick** [comment]
https://github.com/trailblazer/reform-rails/blob/master/lib/reform/form/active_record.rb#L18
