### ISSUE TITLE
Using the simple_form association form helper doesn't work?

### ISSUE THREAD

**Issue by smartygus** [apotonick/reform#122]
If I try to use the `association` helper in a simple_form, I get an `Association not found` error, even if the underlying AR model has that association.

Example:  

```
= simple_form_for @object do |f|
  = f.association :association_name
```

Looking at the simple_form code [here](https://github.com/plataformatec/simple_form/blob/ed3de1c2b566a962697529e824953f6b280e2867/lib/simple_form/form_builder.rb#L550) they seem to check for the association by calling `reflection_on_association` on the class of the object underlying the form. And it seems that `Reform::Form` does not respond to this method, so the `association` helper fails.

Is there something else I should be doing/specifying in my Form object to make this work, or is it just not supported?

Thanks

**Comment by KurtRMueller** [comment]
:( 

Does anybody know how to make collection errors render in simple_fields_for?

Thanks guys.

**Comment by apotonick** [comment]
I have it working for particular fields, e.g. in the [Gemgem application](https://github.com/apotonick/gemgem-trbrb/blob/chapter-9/app/concepts/thing/crud.rb#L38), a form like

```ruby
collection :users do
  property :email
  validates :email, email: true
end
```

will render "email is wrong" next to the correct fields.

Can you quickly explain what does not work for you, @KurtRMueller?

**Comment by KurtRMueller** [comment]
Hmm, here's the relevant form object:


```ruby
class ClusterForm < Reform::Form

  properties :name,
    validates: {
      presence: true
    }

  property :consent_agreement

  collection :sections, populate_if_empty: Section, prepopulate: ->(*) { [Section.new] } do
    properties :class_number,
      :strm,
      :_destroy

    validates :class_number,
      presence: true

    validates :strm,
      presence: true
  end
end
```

If I throw a `binding.pry` in the controller action after calling `@cluster_form.validate(cluster_params)`:

```ruby
[1] pry(#<ClustersController>)> @cluster_form.errors
=> #<Reform::Contract::Errors:0x007fb58b6c04d8
 @base=
  #<ClusterForm:0x007fb5a40efae0
   @changed={"name"=>true, "consent_agreement"=>true},
   @errors=#<Reform::Contract::Errors:0x007fb58b6c04d8 ...>,
   @fields=
    #<Reform::Contract::Fields name="", consent_agreement="", sections=[#<#<Class:0x007fb59ada2788>:0x007fb58cb7a4a0 @model=#<Section id: nil, created_at: nil, updated_at: nil, cluster_id: nil, class_number: nil, carmen_id: nil, strm: nil, subject: nil, catalog_number: nil, description: nil, start_date: nil, end_date: nil>, @fields=#<Reform::Contract::Fields class_number="", strm="", _destroy=false>, @changed={"class_number"=>true, "strm"=>true}, @validation_context=nil, @errors=#<Reform::Contract::Errors:0x007fb58bd1bdc8 @base=#<#<Class:0x007fb59ada2788>:0x007fb58cb7a4a0 ...>, @messages={:class_number=>["can't be blank"], :strm=>["can't be blank"]}>>]>,
   @model=#<Cluster:0x007fb59d936f70 id: nil, created_at: nil, updated_at: nil, name: nil, consent_agreement_id: nil>,
   @validation_context=nil>,
 @messages={:"sections.class_number"=>["can't be blank"], :"sections.strm"=>["can't be blank"], :name=>["can't be blank"]}>
```

Errors will show up for cluster but not for section.

<img width="357" alt="screen shot 2015-07-08 at 7 19 34 pm" src="https://cloud.githubusercontent.com/assets/879734/8584601/56cf3e70-25a6-11e5-9314-c12a3e5df86b.png">

---

Let me know if you want/need more info.

**Comment by KurtRMueller** [comment]
Oh wait, I think I know it it is:

```ruby
        - cluster_form.prepopulate!
        = f.simple_fields_for :sections do |sf|
          = sf.input :class_number, placeholder: 'The section\'s class #'
          = sf.input :strm, label: 'Term', collection: Term.present_or_future.undergrad
```

I'm calling `prepopulate!` on the `cluster_form` which I bet simply resets the sections to be `[Section.new]`.

**Comment by apotonick** [comment]
Sure, `prepopulate!` overrides, unless you check. Are you on Reform 2.0.0?

**Comment by KurtRMueller** [comment]
Rolled back to 1.2 for the time being.

**Comment by apotonick** [comment]
Don't! The `prepopulator` got more helpful in 2.0. I released a rc3 for you. :smile:

**Comment by KurtRMueller** [comment]
Haha, okay. I'll bump and let you know how it goes.

**Comment by KurtRMueller** [comment]
I love you :). In a totally platonic way. Thanks for all of yours and Garrett's hard work. You're helping make my life so much simpler.

**Comment by KurtRMueller** [comment]
Here's the updated form object and view:

```ruby
class ClusterForm < Reform::Form
  include ModelReflections

  properties :name,
    validates: {
      presence: true
    }

  property :consent_agreement

  collection :sections, populate_if_empty: Section, prepopulator: ->(*) { self.sections = [Section.new] } do
    properties :class_number,
      :strm,
      :_destroy

    validates :class_number,
      presence: true

    validates :strm,
      presence: true
  end
end
```

```ruby
        - cluster.prepopulate! unless cluster.errors.any?
        = f.simple_fields_for :sections do |sf|
          = sf.input :class_number, placeholder: 'The section\'s class #'
          = sf.input :strm, label: 'Term', collection: Term.present_or_future.undergrad
```

**Comment by apotonick** [comment]
:heart: <-- totally platonic, of course! :grimacing: 

You should check out page 91-93 in the Trailblazer book talking about prepopulation. I see you're doing that in the view, which is not exactly the way I designed it, but fair enough. In the book, we do that in the controller.

I can further read that you do `if .. errors.any?` - is that to make sure the form is rendered in "validated" context?

**Comment by KurtRMueller** [comment]
`clusters.errors.any?` was a simple way of making sure not to run the prepopulate method if there were any existing errors. The reason being was because reform 1.2 would simply report there being no sections even if there were errors on the form object.

```ruby
# in reform 1.2:
cluster_form.sections.count #=> 0

# in reform 2.0
cluster_form.sections.count #=> 1
```

In reform 1.2, I placed - `cluster_form.prepopulate! ` in the controller. However that never seemed to work... which is why I placed it in the view.

I'll throw it back into the controller and see where it gets me now.
