### ISSUE TITLE
Problems with scope option on validates_uniqueness_of

### ISSUE THREAD

**Issue by jgdreyes** [apotonick/reform#129]
I wanted to add the scope option to `validates_uniqueness_of`.  I pulled down the latest from master and tried it out.  My form was not working as expected.  I took a look at the test that was committed and it looks like there may be a false positive.  

The [test](https://github.com/jgdreyes/reform/commit/87430057f28dc23719d156ea05872781bd1d9f59#diff-9310b60e834f16e483f841518df994f8L53) `it "is invalid when title is taken for the same artist and album"` fails because of the presence validation for `created_at`and not because `title` is taken.  I've added a failing spec here: https://github.com/jgdreyes/reform/commit/87430057f28dc23719d156ea05872781bd1d9f59.

I took a brief look at the reform validator.  It looks like there's a [comment](https://github.com/apotonick/reform/blob/master/lib/reform/form/active_record.rb#L21) to fix the validate method.  So maybe you already have plans to fix this.

I'd love to get an update.  Thanks!

**Comment by fran-worley** [comment]
@jgdreyes ActiveModel validation related code and issues have moved to the reform-rails gem. I'll be closing this here and if you're still having issues can you raise them in the new gem?
