### ISSUE TITLE
Validating belongs_to existence

### ISSUE THREAD

**Issue by dnd** [apotonick/reform#130]
What is the recommended way of validating belongs to relationships? In AR, if I have a User that belongs to a Company, and I set user.company it will set user.company_id, and vice-versa. So when I validate the presence of company_id, it will verify an actual company value is present.

In Reform, validating presence only ensures some value is present. Not whether that value is actually valid. Is there a builtin way to do this? I tried using the validates_existence gem, but it wouldn't work out of the box, since it couldn't do the reflection it needed(it expects an AR object, but is getting a Reform one).

**Comment by spectator** [comment]
I could't find a better way to do existence validation so end up doing this

```ruby
class Reform::Form::ExistenceValidator < ActiveModel::EachValidator
  # Validates existence of a record(s) in the database.
  #
  # === Example
  #
  #   validates :account_id, existence: true
  #   validates :grade_ids, existence: true
  #
  def validate_each(form, attribute, value)
    attribute_name = attribute.to_s.gsub(/(_id)(?=s?$)/, "")
    reflection     = form.model.class.reflect_on_association(attribute_name)

    form.errors.add(
      attribute, :blank
    ) unless reflection.klass.where(id: value).exists?
  end
end

class FooForm < Reform::Form
  property :account_id
  property :grade_ids

  validates :account_id, existence: true
  validates :grade_ids, existence: true
end
```

Should help with `belongs_to` and `has_many` associations.

**Comment by Tab10id** [comment]
UP!
Minor fixes of @spectator code:

```Ruby
class Reform::Form::ExistenceValidator < ActiveModel::EachValidator
  def validate_each(form, attribute, value)
    attribute_name = attribute.to_s.gsub(/(_id)(?=s?$)/, '')
    reflection     = form.model.class.reflect_on_association(attribute_name.to_sym)

    form.errors.add(
        attribute, :blank
    ) unless reflection.klass.where(id: value).exists?
  end
end

Reform::Form::ActiveModel::Validations::Validator.class_eval do
  ExistenceValidator = Reform::Form::ExistenceValidator
end
```

@apotonick how about put this validator near UniqueValidator?

**Comment by samstickland** [comment]
All,

I'm trying to do something similar, except I'd like this to work with deserialize, so I can prepopulate a form (by passing params to deserialize in the controller #new) (rather than the validate approach above)

I've been trying to use this: http://trailblazer.to/gems/reform/populator.html#populator-match-by-id

```
property :artist,
  populator: ->(fragment:, **) {
    artist ? artist : self.artist = Artist.find_by(id: fragment["id"])
  }
```

But that only works if id is nested under artist.

e.g. `{"artist" => {"id" => "1" } }`

But in my case the selection is from a select dropdown, so it's in the form `{ "artist_id" => "1" }`

**Comment by samstickland** [comment]
Ah, L'esprit de l'escalier :)

The is clearly just to put a method into the form object:

```
property :artist_id

def artist
  Artist.find_by(id: artist_id)
end
'''

**Comment by heeton** [comment]
Similar to Sam, this works for me, but it's ugly 

```
class Payment < ApplicationRecord
  class Create < Trailblazer::Operation
    include Model
    model Payment, :create

    contract do
      property :envelope_id, validates: { presence: true }
      property :envelope, validates: { presence: true }

      def envelope
        Envelope.find(envelope_id)
      end
    end

    def process(params)
      validate(params[:payment]) do |form|
        form.save
      end
    end
  end
end
```

**Comment by fran-worley** [comment]
As of Reform 2.2.0, Active Record related code was moved to the trailblazer/reform-rails gem. I am therefore closing the issue as it no longer relates to this repository.

Thanks for all of the contributions to this issue.
