### ISSUE TITLE
How to use reform without ActiveRecord Model ?

### ISSUE THREAD

**Issue by rtcoms** [apotonick/reform#131]
I am trying to create a form with backend validations which is not associated with any model . 

Documentation says :
# initialize always requires a model that the form represents.

How can I use reform for this case ?

**Comment by LeandroTk** [comment]
I tried with nil and I received 
```
NoMethodError: undefined method `name' for nil:NilClass
```
I tried with OpenStruct and received 
```
NoMethodError: undefined method `read_attribute_for_validation' for #<OpenStruct email="manage@email.com">
```
Tried with only virtual.. didn't work. Tried with both virtual and empty.. didn't work.

**Comment by apotonick** [comment]
Hey @LeandroTk, you must be using a weird validator that accesses `#name`. Are you using `uniqueness: true`?

Please make sure to use Reform 2.0, `virtual: true` and `unique: true` instead of `uniqueness: true` in case you're using this, documented here: http://trailblazerb.org/gems/reform/validation.html#uniqueness-validation

:beers:

**Comment by LeandroTk** [comment]
Thanks @apotonick ! I was using uniqueness.
Now I changed to unique, as you said.

It fixed that error, but when I use 

```
def initialize
  super(nil)
end
```

I receive 

```NoMethodError: undefined method `where' for NilClass:Class```

And if use OpenStruct

```
def initialize
  super(OpenStruct.new)
end
```

I receive

```NoMethodError: undefined method `where' for OpenStruct:Class```

I don't know if I can use FormObject without passing a model

**Comment by apotonick** [comment]
That doesn't work, of course, as the form has no idea which model class to use for the database uniqueness query. If you use ActiveRecord features then you need an ActiveRecord model, it can be empty, but it has to be there. Sorry, that's the price you pay for AR's magic.

That will work.

```ruby
SongForm.new(Song.new)
```

**Comment by apotonick** [comment]
I have an idea how we could fix this in the future, but then you would have to specify `::model`.

```Ruby
class SongForm
  model Song

  property :name, virtual: true
  validates :name, unique: true
end

SongForm.new(nil) # this will work, once we implemented it... 
```

What do you prefer? :grimacing:

**Comment by LeandroTk** [comment]
Hum, interesting. It makes sense!
I removed the ```unique: true``` from my UserForm class and I will try to use the model uniqueness validation, only.

What I'm trying to do is to implement a UserForm that can represents all users in the platform (Investor, University, Researcher, etc) for a basic signup.
So I overwritten the Reform #save method to something like that:

```
def save
  resource = case(user_type)
  when 'investor'
    Investor.new({ name: name, email: email, password: password })
  when 'company'
    Company.new({ name: name, manager_name: manager_name, email: email, login: login, password: password })
  when 'affiliation'
    Affiliation.new({ name: name, manager_name: manager_name, email: email, login: login, password: password })
  end

  resource.save
end
```

How can I pass the uniqueness errors from model to form object? (Am I making myself clear?)

**Comment by apotonick** [comment]
Hm, I think you should use sub classes for different "models" so you don't need to have ugly deciders in your code and can use polymorphism.

I will write about that in the _Authorization_ chapter of the Trailblazer book, but if you're interested, I can give you some code examples here, too! :laughing:

**Comment by LeandroTk** [comment]
Yeah, I'm interested, @apotonick ! :smiley:

**Comment by exsemt** [comment]
You can use OpenStruct and generate the object from hash if you need it.

```
  def initialize(hash)
    attrs = JSON.parse(hash.to_json, object_class: OpenStruct)
    super(attrs)
  end
```
