### ISSUE TITLE
Pre-populated empty property?

### ISSUE THREAD

**Issue by dnd** [apotonick/reform#140]
I have a property that doesn't exist on the model, and I have defined it as `property :headquarters_location, empty: true`, but I need to pre-populate it with a combination value from the main model. I tried using :populator and :populate_if_empty, but they didn't seem to ever get called.

Should I be manually overriding the getter for headquarters_location? If so, how do I ensure my setup only happens at initialization? I was going to check for nil, but it's perfectly acceptable to nullify the value, so I think that might cause problems if it can't just be done when the form is initialized.

**Comment by apotonick** [comment]
Hi Steve, I have had a few beers.. I mean thoughts about this. I am contemplating the following.

## Idea for Render-only Population

In the form we have a nested model `User`. The composing `Comment` doesn't have this user instance, yet, when rendering the initial form.

```ruby
class CommentForm < Reform::Form
  property :user, populate_for_render: -> { User.new } do
    # ..
  end
end
```

Then, when rendering a ***new*** form to be presented with a nested user form, you need to instruct the form to setup itself for rendering.

```ruby
comment = Comment.new # NO nested user!

CommentForm.new(comment).render!
```

The `#render!` call (or, is `#prepare!` better?) will then populate the form using `:populate_for_render`. Cool?

**Comment by apotonick** [comment]
Or, what about `#prepopulate!`? The name has to make it obvious that this should NOT be called when `validate`ing!

**Comment by zavan** [comment]
Nice!

**Comment by apotonick** [comment]
This is now implemented: http://kicksology.net/blog/2015/1/11/wtf-is-a-product-manager
