### ISSUE TITLE
Exception when invalid date

### ISSUE THREAD

**Issue by zubin** [apotonick/reform#142]
Given a reform class with a date input, eg:

    class SomeForm < Reform::Form
      property :starts_on, type: Date
    end 

When a user submits an invalid date (eg 31 Sept), an exception is raised when reform parses the date params. The exception is simply "invalid date" (ie no exception class). I think it's raised by Date.

Here's the relevant backtrace:

    reform (1.0.1) lib/reform/form/multi_parameter_attributes.rb:30:in `new'
    reform (1.0.1) lib/reform/form/multi_parameter_attributes.rb:30:in `params_to_date'

**Comment by fran-worley** [comment]
@zubin any update? I'm going to close this as Multi-parameter attribute handling has moved to reform-rails.

If this is still not working as expected can you create a new issue there?
