### ISSUE TITLE
Bug saving mongoid embedded documents

### ISSUE THREAD

**Issue by jreinert** [apotonick/reform#143]
Took me quite long to locate the bug.. I was using a nested form object in an update action so i populated the form object with the model, called `#validate` and then `#save` (if `#validate` returned `true`). This however didn't persist the changes. Only submitting the form again did. So i ended up calling `#save` twice to work around this. I suspect this has something to do with mongoid's embedded documents implementation and tbh I don't know if this is a bug with mongoid. I didn't encounter this bug before using reform though, so I'm suspecting reform. I'll be happy to provide additional info if necessary.

**Comment by tilsammans** [comment]
Came here via a search, I have this exact same problem too, and I am not using reform.

A localised field only persists when saved for the second time, and all times thereafter.

**Comment by apotonick** [comment]
Thanks! You should use Reform, though, @tilsammans! :grimacing:

Thanks for reporting that!

**Comment by tilsammans** [comment]
> You should use Reform, though, @tilsammans

Yes, I should! And I _am_ on different projects, too. (Don't tell the Ruby thought police)
