### ISSUE TITLE
Order of property and alias is unintuitive

### ISSUE THREAD

**Issue by bethesque** [apotonick/reform#152]
It currently reads "expose [alias] as [real_name]"
```ruby
class Form < Reform
  property :customer_reference as: :cust_ref
end
```
instead of "expose [real_name] as [alias]"
```ruby
class Form < Reform
  property :cust_ref, as: :customer_reference
end
```

This is confusing as 1. the pseudo englishness of the code does not make sense, and 2. Representable, Roar and Grape Entity all work the other way around, so it is likely to catch a lot of people out.

**Comment by apotonick** [comment]
`:as` is now `:from`.

**Comment by bethesque** [comment]
:+1:
