### ISSUE TITLE
overriding properties

### ISSUE THREAD

**Issue by ginter** [apotonick/reform#153]
I previously was able to override a property when saving by defining a method. ie.

property :state

def state
  'completed'
end

form.save # state = 'completed' is writtten

Was this behavior intentionally changed?

**Comment by kalashnikovisme** [comment]
@apotonick `sync` option is really good :cake:

**Comment by apotonick** [comment]
Hey, wait, we removed `:sync` in Reform 2.0 - are you saying you want it back, @kalashnikovisme ?

**Comment by kalashnikovisme** [comment]
@apotonick it would be nice. Because there is some cases, where this can be useful. For example:

VoteAPI.
*vote_form*

```ruby
class VoteForm
  property :difference, sync: -> (identificator) { model.difference = difference_size(identificator) }

  private

  def difference_size(identificator)
    case identificator
    when 'like'
      admin? ? 5 : 1
    when 'dislike'
      admin? ? -5 : -1
    end
  end
end
```

I think this code must if form, not in controller.

**Comment by apotonick** [comment]
Well that is code that goes into the operation normally in TRB. :grimacing:

**Comment by kalashnikovisme** [comment]
@apotonick please, explain, what is *TRB*?

**Comment by apotonick** [comment]
TRB == Trailblazer == http://trailblazer.to

**Comment by kalashnikovisme** [comment]
@apotonick oh, thanks :+1:

**Comment by JamesLivengood** [comment]
If I want to do something like ginter posted in the OP, 
```
property :state

def state
'completed'
end
```

But it's a property of a nested object, how can I do that? It doesn't work when I just put the property name

**Comment by JamesLivengood** [comment]
Nvm, for anyone looking for how to do the above, you need to put that actual method inside the nested block where you're declaring your nested object properties
