### ISSUE TITLE
#{property}_before_type_cast

### ISSUE THREAD

**Issue by codesnik** [apotonick/reform#158]
I'm thinking it would be useful to add an optional layer of before_type_cast properties, where original, not coerced values are stored, exactly as params

Rails activemodel/lib/active_model/validations/numericality.rb already tries to peek into _before_type_cast properties if object respond to them, for some reason. Custom validators could do this too.

But actually I have a bigger goal in mind: I'd like to be able to present user with what he typed, to give a chance to correct data, instead of blank field or something worse. Especially in cases when there's a problem coercing string value to actual type *and back*.

_before_type_cast layer on properties could help with it, I think.

Other usecase: localized forms! for example, In Russia we write "10,23" instead of "10.23", and it's a common problem of losing fractional part on a simple "to_i", displaying data "incorrectly", etc.. But it's a matter for another issue.

Any thoughts before I try to implement it?

**Comment by fran-worley** [comment]
Any update @codesnik ? It's been a while and looks like your issue has been resolved so I'm going to close this. Feel free to reopen if you need 😄.

**Comment by codesnik** [comment]
No update, thank you.

чт, 7 июля 2016, 9:31 Fran Worley <notifications@github.com>:

> Closed #158 <https://github.com/apotonick/reform/issues/158>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/apotonick/reform/issues/158#event-715268031>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAARoG_34NoGmZUbKeu-2LS7NqyEN_VUks5qTI8-gaJpZM4C2w8A>
> .
>
-- 
Alexey Trofimenko, CIO, Busfor
