### ISSUE TITLE
Nested forms and composition?

### ISSUE THREAD

**Issue by Azdaroth** [apotonick/reform#170]
Hi Nick, is it possible to use forms with composition as a nested form? I tried doing things like:

``` ruby
  collection :investments, form: Investment::OmApiForm, populate_if_empty: lambda { |fragment, args|
    investment = model.investments.where(name: fragment["name"]).first_or_initialize
    {
      investment: investment,
      profile: investment.profile_or_build_one
    }
 }
```

but couldn't achieve anything working properly.

**Comment by apotonick** [comment]
I was thinking about this. How would the initialization of this form look like? When you first setup this form, how would the nested form know where to get the composition parts from? Remember, in setup, there's no `fragment`.

**Comment by fran-worley** [comment]
As this seems to have gone stale I'm going to close. @Azdaroth feel free to reopen if you've got anything to add.
