### ISSUE TITLE
Abstracting collections best practice?

### ISSUE THREAD

**Issue by pelted** [apotonick/reform#174]
I'm posting this as a new issue that I can use as a possible wiki example for dealing with similar situations. (similar to the current "How to do a multipart updatable date")

This is a very simplified example for illustration:
I have a Contact AR model which has_many phone numbers (PhoneNumber)

```ruby
class Contact < ActiveRecord::Base
  # first_name
  # last_name

  has_many :phone_numbers
end

class PhoneNumber < ActiveRecord::Base
  # category
  # number

  scope :office,   -> { where(category: :office) }
  scope :mobile,   -> { where(category: :mobile) }
  scope :fax,      -> { where(category: :fax) }

  belongs_to :contact
end
```

The form view looks something like this
```erb
<%= form_for @reform do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>

  <br>

  <%= f.input :office_number %>
  <%= f.input :mobile_number %>
  <%= f.input :fax_number %>
<% end %>
```

I found it very common to need this sort of abstraction to the end user while maintaining more normalized database data. *(contact and phone_numbers tables)*

My first approach to solving this in the past had been rather fat controller and models with very poor coupling to deal with this. I later moved to service objects and abstracted much of the serialization and creation into those. Now I'm exploring *Form Objects* and **Reform** for a new project as a better approach, but I keep falling back into old patterns. (see below)

Starting point of the Reform class that I know isn't right
```ruby
class ContactForm < Reform::Form
  reform_2_0!
  
  property :first_name
  property :last_name

  property :office_number, virtual: true
  property :mobile_number, virtual: true
  property :fax_number, virtual: true

  def submit
    self.save do |hash|
      # possibly create the nested objects
    end
  end

  def sync
    # probably override sync to handle back and forth
    result = super
  end
end
```

So the big question is what is the best approach here? Maybe a **PhoneNumberForm** class to deal with the specifics and validation of a PhoneNumber?

Maybe I'm just tired and completely taking the wrong approach for how the FO pattern is supposed to work.

**Comment by fran-worley** [comment]
Any update @pelted ? It looks like nick resolved your query so I'm going to close. Do reopen if you need. 😄
