### ISSUE TITLE
How to delete nested item from form collection properties?

### ISSUE THREAD

**Issue by badenkov** [apotonick/reform#179]
For example i have Album and a few Song in them, and i need add one song and remove two.

    class Album < ActiveRecord::Base
       has_many :songs
    end
 
    class Song < ActiveRecord::Base
    end

    class AlbumForm < Reform::Form
      collection :songs do
         title
       end
    end

And test for example:

    album = Album.create(songs: [Song.new(title: 'song 1'), Song.new(title: 'song 2')])
    attrs = {
      songs: [
        { title: 'song 3' }
      ]
    }

    put :update, song: attrs

    expect(album.songs.count).to eq(1)

I mean maybe _destroy attributes, as in accept_nested_attributes

**Comment by apotonick** [comment]
In chapter 7 of the book is an example how to do it manually. Here's the code: https://github.com/apotonick/gemgem-trbrb/blob/chapter-7/app/concepts/thing/crud.rb#L81

The chapter will be published in the next 10 days.

**Comment by apotonick** [comment]
This is explained in chapter 7. Let me know if you still need help!!! :beers:
