### ISSUE TITLE
Scoped uniqueness validation not working

### ISSUE THREAD

**Issue by zavan** [apotonick/reform#189]
I'm working on a project with Trailblazer (from master). I have the following operation:

```ruby
class Customer::Create < Trailblazer::Operation
  include CRUD, Responder

  model Customer, :create

  contract do
    include Reform::Form::ModelReflections

    model Customer

    property :shipper_id
    property :code, validates: {presence: true, uniqueness: {scope: :shipper_id}}
    property :name, validates: {presence: true}
  end

  def process(params)
    validate(params[:customer]) do |f|
      f.save
    end
  end
end
```

The scoped uniqueness validation doesn't work, I get a `PG::UniqueViolation: ERROR: duplicate key value violates unique constraint...` because of my uniqueness database constraint.

I've also tried the other ways (all of them with and without the `_id`): 

```ruby
validates :code, uniqueness: {scope: :shipper}
validates_uniqueness_of :code, scope: :shipper
```

None of them seems to work. Any idea?

**Comment by apotonick** [comment]
That's because AR's uniqueness validations are implemented poorly and super hardcore coupled to ActiveRecord's non-existent API.

Write your own uniqueness validator for now until we come up with a our own or use `Lotus::Validations`.

[Duplicate](https://github.com/apotonick/reform/issues/129), closing this.

**Comment by zavan** [comment]
I understand. Thank you, Nick.

**Comment by apotonick** [comment]
Yeah, sorry for that inconvenience. I've tried several workarounds but they all ended up in too much patch code. Beside that, AR's uniqueness validation is leaky as it can create a race condition. And we could fix that in Trailblazer! The `Operation#validate` method could, for example, wrap the validation/save into a DB lock. In pure Rails, if two users with the same email send a request at the same time, it blows up!

**Comment by zavan** [comment]
No problem!

Do you plan on creating a "validations" gem or something like that?

**Comment by apotonick** [comment]
I will start playing with Reform + `Lotus::Validations`, soon. Do they already include a uniqueness validator?

**Comment by zavan** [comment]
@apotonick Nope :/

From their README:
"Uniqueness validations aren't implemented because this library doesn't deal with persistence. The other reason is that this isn't an effective way to ensure uniqueness of a value in a database."

**Comment by apotonick** [comment]
Yeah, we should write our own! I'm picturing something as follows.

```ruby
class Operation
  def validate
    DB.lock do # no idea how, but it works somehow.
      contract.validate(params) # here, the uniqueness is tested, IN A LOCK.
      yield # this is where contract.save is called, still in the lock.
    end
  end
```

Since an operation wraps all that, it should be extremely simple (and 100% safe) to implement that. Interested, @zavan ? :grimacing:

**Comment by zavan** [comment]
@apotonick This is going to be a very busy week for me, but think I can handle this next week (or even this week if I find some time) :wink:

**Comment by apotonick** [comment]
No worries, @gogogarrett is working on a new uniqueness validator already, you can think about the DB lock (if you want).

**Comment by zavan** [comment]
@apotonick On a side note, I didn't know about this Lotus Framework, it seems really cool. What do you think about it?

I know it's differs a lot from trailblazer, because trailblazer is just a thin layer on top of other frameworks and Lotus is a whole new framework (where trb can also be used...).

**Comment by apotonick** [comment]
Lotus is fantastic, but it's too low-level. It's a great chance for a clean, new HTTP framework and Trailblazer can totally work in Lotus. However, Lotus is lacking a domain layer, an integration of view models with that domain layer, and I think they will end up using Reform as the validation layer, anyway.

I honestly can't wait to let operations and cells run in a `Lotus::Action`, though!

**Comment by zavan** [comment]
@apotonick That's what I thought. I think integration with trb (and cells, reform etc) will make it my dream framework.

**Comment by zavan** [comment]
hey @apotonick, this has been mentioned on the lotus chat and we had a small discussion about it https://gitter.im/lotus/chat (you will probably have to scroll up a little)

**Comment by fernandes** [comment]
hey @zavan 

somewhere in past I had to deal with uniqueness validation, so I ended up doing something like this (simplified the example to be easier to understand), but was something like User having uniqueness validation on document (you know, we have just only one CPF heheh)

its something like this:

```ruby
class Create < Trailblazer::Operation
  contract do
    property :document
    validate :is_document_unique?
    model :user
    
    def is_document_unique?
      if User.where("document = ? and id <> ?", document, self.id).count > 0
        errors.add(:document, "is already in use")
      end
    end
  end

  include CRUD
  include Responder
  model User, :create

  def process(params)
    validate(params[:user]) do |f|
      f.save
    end
  end
end
```

hope it helps you

ps: Testing is damm easy, just test your operation in a context where the record is the first one being saved, then run the operation and try to save again, op.form will be with errors

**Comment by zavan** [comment]
@fernandes Thanks, that's what I'm doing for now :smile: 

Only difference is I'm using `Model.exists?`, it's a little bit cleaner:

```ruby
if Customer.exists?(code: code, shipper_id: shipper_id)
  errors.add(:code, "is already in use for this shipper")
end
```

**Comment by fernandes** [comment]
You can write a scope on AR and use it... just would like to make the example simple to understand, all other approaches are personal preferences... if you got it, I'm happy :)

**Comment by zavan** [comment]
I was thinking about this and it came to my mind: 

"Why don't I simply rescue the exception raised by the DB adapter when a unique constraint is violated (`PG::UniqueViolation` in PostgreSQL), parse the error message to get the invalid columns (since these exceptions doesn't provide them) and add them to the errors hash?! This way we don't need selects or locks, since the DB does this job better than anyone with the unique constraints..."

I started writing some code to try this out, and in my research I found [this](https://github.com/Shopify/activerecord-rescue_from_duplicate), which was extracted from Shopify.

It can work with Rails uniqueness validation + DB constraint, or **just the DB constraint**.
Aaaaand, It works just the way I described.

It is `ActiveRecord::Base` specific, but we could generalise [this code](https://github.com/Shopify/activerecord-rescue_from_duplicate/blob/master/lib/rescue_from_duplicate/active_record/extension.rb) into a gem and it would work perfectly with anything, including Reform. :smiley:

The only "problem" is: The dev would need to create the DB constraint (which in my opinion must be created anyway).

**Comment by apotonick** [comment]
This doesn't work as the validation happens _before_ saving

 It's actually not that hard to implement, look at my diagram.

```ruby
Operation#process
  DB.lock
    Operation#validate
      Reform#validate
        Song.where(title: "With Love, The Underground").size == 0
      Reform#save
```

The design of the operation is the perfect place to wrap that into a lock. And this also stresses that a real business validation is embedded into the entire workflow - it is just not a "validation" as Rails tries to do it.

The `where` part needs to be implemented in Reform as a validation and has the same race-condition problem as it doesn't lock or anything. However, the real power comes in an operation which gives you a lock for free.

Again, catching the exception doesn't help as it's "too late"! When saving, we're in a different state of the business workflow.

**Comment by zavan** [comment]
Damn, hadn't thought it through.

I'm messing with Lotus+Trailblazer right now, when I finish it I'll do this.
