### ISSUE TITLE
Question: Validating Collections

### ISSUE THREAD

**Issue by jstoup111** [apotonick/reform#190]
Is there a way to validate the length of a collection properly?  Just like rails ActiveRecord, Reform has a similar issue with validating the length of the collection.  I.E.

Given a model with
```
validates :foos, length: { minimum: 1 }
```

When you make a call to ```form.validate``` it will still have 1 foo in the collection.  However the foo has a property ```marked_for_destruction``` which returns true.  Is there a way to write a custom validation in a form to handle this, or is there a way to handle validating that the collection actually has 1 item.

**Comment by apotonick** [comment]
Hey James,

not sure if I understand correctly. The validation you're suggesting works in Reform, too! Is the problem that destruction thing?

You can _always_ write a custom validation, [chapter 6 of the book](https://leanpub.com/trailblazer) is gonna discuss that. It works exactly like custom validations in models.

However, can you elaborate a bit further on what is the actual problem? Prost!

**Comment by jstoup111** [comment]
Hi Nick,

A little bit of background.  I'm using your Reform gem in conjuntion with Cocoon as I need a good way to dynamically add additional nested models.  As such I'm doing something similar to this https://github.com/apotonick/reform/issues/86#issuecomment-57059716.  

I've created a virtual property _destroy.

Save looks like this.
```
def save
    # you might want to wrap all this in a transaction
    super do |attrs|
      if model.persisted?
        to_be_removed = ->(i) { i[:_destroy] == '1' }
        ids_to_rm = attrs[:foos].select(&to_be_removed).map { |i| i[:id] }

        Foo.destroy(ids_to_rm)
        foo.reject! { |i| ids_to_rm.include? i.id }
      end
    end

    # this time actually save
    super
  end
```

Now for that background, the way that active record validations work for collections is that 

```
validate :foos, length: { minimum: 1 }
```

will cause a #validate to return true if it has a length of one.  This is all fine and dandy until in my case, I have to pass some sort of way to destroy my object.  Since Reform does not have a way to handle this currently, I have to implement this myself.

Normally in an ActiveRecord::Model all you would do to run validations would be:

```
def foo_length
      remaining_foos= foos.reject(&:marked_for_destruction?)
      errors.add :base, 'At most 3 foos' if remaining_foos > 3
      errors.add :base, 'At least 1 foo' if remaining_foos < 1
  end
```

This accurately runs the validation because destroying it off of the object still has the record in the collection.  ActiveRecord sets a flag marked_for_destruction? indicating that this record should be destroyed.  Because of this, one should account for that in their collection validations since a record that will be deleted could cause the model to be invalid later.

Now the problem is that Reform doesn't allow you to do this currently, as far as I know.  My understanding maybe limited here, however, since #validate does not sync the model, how am I to accurately run my validation?  Reform doesn't indicate that any of my models need to be destroyed, so I must do it manually.  I do not have access to the updated values that I would get in the save block.  Unless I'm misunderstanding there's no way to know in Reform whether one of my models is set to be destroyed from the server and there isn't a way for me to set it.  How can I set a flag that I have access to in my validation code to notify me that my model is supposed to be destroyed?

**Comment by apotonick** [comment]
You have access to the input when you define it as a property.

```ruby
collection :foos do
  property :title
  property :_destroy, virtual: true
end
```

Then, in the validation method.

```ruby
def validate_foos
  foos.first._destroy
end
```

**Comment by jstoup111** [comment]
Doh.  That makes a lot of sense.  I've adjusted accordingly.  I appreciate the help as I knew I was missing something.  I'd be curious to see how deletion gets implemented in the future release.

**Comment by apotonick** [comment]
It will be handled in Disposable, and not Reform itself, as this makes it reusable for API code, too. Reform will just trigger it in `save`.

I need a year off to code all the ideas I have. 😜

**Comment by apotonick** [comment]
BTW, isn't it a bit misleading to _delete_ items when `validate`ing? That must go to `sync` or `save`. I guess `sync` is the better place as this is the documented place in Reform where we write to models?!

**Comment by jstoup111** [comment]
Let me know I'd be willing to help out with anything and can have some extra time. 

Regarding the sync thing I do find it awkward that the validation has to check to see which models in the collection are set to be destroyed.  I know the HTTP request will pass the _destroy flag. I'm not sure if this is an active record thing or a rails thing however but I should look into it.  I'm not sure if it could still be orm agnostic though but maybe the validations could work properly I.e. If you're deleting a the only record on a collection that has length validation it should be invalid.  Could be a rails, active record or disposable thing. 

I'm going to reopen this if it becomes something worth doing as part of disposable.

**Comment by fran-worley** [comment]
As far as I'm aware, the 'reform' way of doing this is to set the populator for your collection to check for a destroy flag in your fragment, call delete on the collection twin object and stop any further processing of that fragment.

With that approach your issue goes away as the collection item no longer exists.

I know a lot of hacks out there exists on trying to get cocoon to work with reform and it makes me sad... I've got complex nested collections working beautifully without cocoon or a accepts_nested_attributes_for in site! If your interested I have a gist which includes all the relevant code to help you DIY.

**Comment by fran-worley** [comment]
As of Reform 2.2.0, Active Record related code was moved to the trailblazer/reform-rails gem. I am therefore closing the issue as it no longer relates to this repository.

Thanks for all of the contributions to this issue.

**Comment by kofronpi** [comment]
@fran-worley would be awesome to copy the gist in the `reform-rails` wiki as this is a common problem ! :)

**Comment by fran-worley** [comment]
@kofronpi which gist are you referring to? There isn't a wiki for 'reform-rails' just yet.

**Comment by kofronpi** [comment]
@fran-worley the one your refer to at the end of your comment from July 7, 2016 on this very issue :)
