### ISSUE TITLE
nested form problem

### ISSUE THREAD

**Issue by gogainda** [apotonick/reform#191]
I have a model Question (user_id, consultant_id, body) and  a form for creation 5 questions for the specific consultant. Initially, form save works greate - first questions being created but when I want to add new questions for the different consultant then previous questions get replaced with new ones.
I tried to overcome it with this code
```
def new_quesions_form
f = QuestionsForm.new(current_user)
f.questions  = []
5.times { f.questions << current_user.questions.build(consultant_id: consultant.id) } #new consultant id
end
```
but it does not work, previous questions get replaced with new one

What do I wrong?

**Comment by apotonick** [comment]
You're lucky because that's exactly what I do in chapter 5 of the Trailblazer book: We have a `Thing` that can have up to 3 authors, so this should pretty much reflect what you're trying to do.

The chapter will be out beginning next week, is that OK with you?

**Comment by gogainda** [comment]
Maybe you have quick solution for my problem?

**Comment by apotonick** [comment]
I'll hit you up once I finished the example in gemgem-trbrb. Sorry, I have to play with it myself, first, before giving out a valid answer, but it's gonna be awesome.
