### ISSUE TITLE
Example with money

### ISSUE THREAD

**Issue by gogainda** [apotonick/reform#200]
I have a form like 
class PriceForm < Reform:Form
    property :price_euros, empty: true # in the db i have only price column
    validates :price_euros, numericality: { only_integer: true }
end

Firstly, I want to validate that price_euros is integer and after that I want to write price in cents to the db.
I dont know how to implement the last part of the previous sentence.

**Comment by apotonick** [comment]
Hi Igor!

You can add a `:sync` hook to do that.

```ruby
property :price_euros, sync: ->(value) { model.price_cents = value/100)
```

This is not officially documented, yet. I advice you to regularly check the CHANGES file and my blog. BTW, we're going to discuss that in my book, too. https://github.com/apotonick/reform/blob/master/CHANGES.md#120
