### ISSUE TITLE
Nested field errors displaying strangely

### ISSUE THREAD

**Issue by radar** [apotonick/reform#201]
I have a Client model which has a form object which defines a collection of `FamilyMember` objects.

```
module Clients
  class Step2Form < Reform::Form
    collection :family_members, populate_if_empty: FamilyMember do
      properties :given_name, :family_name, :date_of_birth, :relationship, :gender

      validates :given_name, :family_name, :date_of_birth, :gender, presence: true
  end
end
```

When the validation fails for the nested records, I see this:

![screen shot 2015-02-11 at 8 58 23 pm](https://cloud.githubusercontent.com/assets/2687/6144935/c7c93e8a-b230-11e4-8bbb-2e4f4334d28b.png)

The code I'm using to output those error messages is this:

```html+erb
<% if object.errors.any? %>
  <div class='alert alert-danger'><%= pluralize(object.errors.count, "error") %> prevented this form from being saved:
    <ul>
      <% object.errors.messages.each do |field, errors| %>
        <li><%= field.to_s.titleize %> <%= errors.to_sentence %></li>
      <% end %>
    </ul>
  </div>
<% end %>
```

What can I do to make the field name print out "neatly"? For example, instead of "Family Members.Given Name can't be blank" I want "Family members Given name" or something similar to that.

I would expect that this would be done in the `each` call, by some code that looks like:

```ruby
def each
  messages.each_key do |attribute|
    self[attribute].each { |error| yield self.class.human_attribute_name(attribute), Array.wrap(error) }
  end
end
```

But that doesn't appear to be the case.

So how do I get a clean name for these attributes in my error messages?

<3

**Comment by apotonick** [comment]
Ryaaaaaannnn! :heart: 

It would be interesting to see how Rails does it. I guess they filter out the dot somewhere but I personally have no clue. I still have issues with the way errors get displayed in some weird cases, probably because we don't use Rails code directly.

Go, figure it out, anyone!

**Comment by fran-worley** [comment]
If anyone is interested, this is how rails does it:

https://github.com/rails/rails/blob/ccbc98e37dcc11ad5150b93dcee8008bc94aa83a/activemodel/lib/active_model/errors.rb#L440-L441

**Comment by fran-worley** [comment]
As of Reform 2.2 all active model / active record related code has moved to the reform-rails gem.

If you're still experiencing this issue, please can you reopen it in the correct gem. Thanks 😺
