### ISSUE TITLE
Custom Validation

### ISSUE THREAD

**Issue by tommy7xo** [apotonick/reform#202]
I have model with custom validation. I have a validator class and inside the class body I have:
`validates_with MyValidator`
How to use this validator with form model?
I put to the Form model:
`extend ActiveModel::ModelValidations
    copy_validations_from MyModel`
But this is not working at all. It returns:
`ArgumentError - Unknown validator: 'MyValidator'`

**Comment by apotonick** [comment]
Hi Tommy,

you don't need the `ModelValidations` module in your form. You have to make sure the `MyValidator` name sits in the right namespace: `ActiveModel::Validations::MyValidator`. This is not Reform's fault but an `ActiveModel::Validations` limitation.

**Comment by fran-worley** [comment]
Hi Tommy, I hope you got this sorted. I'm going to close this as it's been a while but do reopen if you need. 😄
