### ISSUE TITLE
Validating field only if there is content in input

### ISSUE THREAD

**Issue by wellincall** [apotonick/reform#203]
I am using version 1.2.4. I have the following declaration in my form:
```ruby
property :contract_extension, validates: {numericality: true}
```
How could I validate this field only if the input is not blank?

**Comment by apotonick** [comment]
Wow, this is not documented, yet: https://github.com/apotonick/reform/blob/master/CHANGES.md#new-stuff

You can use `:skip_if`.

**Comment by apotonick** [comment]
Ah sorry, that is only for deserialisation. You can use the following.

```ruby
validates :contract_extension, numericality: true, if: ->(*) { contract_extension.present? }
```

The block is executed in form context allowing you to access all kinds of properties.

**Comment by wellincall** [comment]
Thanks, Nick!
