### ISSUE TITLE
Virtual attribute throws undefined method error

### ISSUE THREAD

**Issue by icatcher-at** [apotonick/reform#205]
I have the following setup:
```ruby
class CopyForm < Reform::Form
  property :id
  property :date_interval, virtual: true
end
```

When I render the form:
```ruby
= simple_form_for @form do |f|
  = f.input :date_interval, as: :string
```

Rails throws the following exception:
`undefined method 'date_interval'`

If I understood the documentation correctly, Reform shouldn't try to query the model for virtual attributes? I'm using Reform 1.2.6.

**Comment by apotonick** [comment]
You have to add 

```ruby
class SongForm < Reform::Form
  reform_2_0!
```

so it picks up the new semantic of `:virtual`.

**Comment by simonc** [comment]
Maybe adding this to the readme until it's useless could be a good idea.

Do you want a PR for this? :)

**Comment by apotonick** [comment]
Yes please!!!!! :heart:

**Comment by simonc** [comment]
Here it is :) https://github.com/apotonick/reform/pull/213
