### ISSUE TITLE
Form path is failing

### ISSUE THREAD

**Issue by enricribas** [apotonick/reform#206]
So I'm new to reform but...

I get 
```ruby
undefined method `provider_as_editors_path' 
```
from
```ruby
<%= form_for @form do |f| %>
```
using 
```ruby
def new
  @form = Provider::AsEditor.new(Provider.new)
end
```
and 
```ruby
class Provider
  class AsEditor < Reform::Form

  property :name
...
```

I would imagine that the form object would behave like AR and trick forms into returning "provider_path" instead of "provider_as_editors_path" since that is the path of the wrapped model?

I'm sure I'm missing something obvious but confused right now or I've misunderstood how this is supposed to work. 
Thanks.

**Comment by BlackFoks** [comment]
You can try this:

```ruby
  class Provider
    # ...
    model :provider
  end
```

I hope it would help.

**Comment by enricribas** [comment]
Sorry. I guess I should have mentioned that Provider is an ActiveRecord class defined elsewhere. 

Did you mean to add model :provider to the form?

ie.
```
class Provider
  class AsEditor < Reform::Form
  model :provider
  property :name

```

I will try that.

**Comment by apotonick** [comment]
This is how it works: https://github.com/apotonick/reform#activemodel-compliance

BTW, this is all explained in the Trailblazer book, too! :stuck_out_tongue_winking_eye:
