### ISSUE TITLE
has_one with NOT NULL column fails on save 

### ISSUE THREAD

**Issue by philipnery** [apotonick/reform#210]
So I have two tables, **User** and **UserProfile**.
**UserProfile** has a user_id with null: fase

When creating my user, it fails because user_id is NULL.
This is my code for create in my user controller

```
...
def create
    user = User.new
    user.build_profile
    @form = UserForm.new(user)

    if @form.validate(params[:user])
      @form.save # ERROR
...
```
I think the profile is saved before the user so it still has no id.
I have changed the code to this as a workaround (or maybe this is the right way)

```
...
def create
    user = User.new
    user.build_profile
    @form = UserForm.new(user)

    if @form.validate(params[:user])
      @form.save do |nested|
        user.profile.assign_attributes(nested[:profile])

        user.save!
      end 
...
```
Is this a bug?

**Comment by apotonick** [comment]
Not a bug, but not really Reform's issue since Reform is a form object and not a AR abstraction. This kind of fine-tuning will go into disposable.

Why don't you just do

```ruby
@form.sync # writes attributes to models
@form.model.user.save
@form.model.save # or whatever order you need.
```

**Comment by apotonick** [comment]
BTW, your controller looks like you want to give Trailblazer a go!
