### ISSUE TITLE
Is there any way to lazily-access properties?

### ISSUE THREAD

**Issue by shepmaster** [apotonick/reform#211]
I have a model that delegates the `client_name` property to an associated model, but only sometimes. It appears that Reform eagerly accesses all the defined properties, even if those properties aren't used by anything:

```ruby
class FooForm < Reform::Form
  property :bar
end
 
class Bar
  def bar
    raise "called"
  end
end
 
FooForm.new(Bar.new)
#=> RuntimeError: called
```

Is there some way of specifying a property that doesn't access the model until the corresponding accessor is used on the form object?

**Comment by apotonick** [comment]
No, sorry, this is impossible ATM. It would be easy to change this for plain attributes but then with nested objects we would get into trouble. Why do you specify those fields as properties if you don't need them, I wonder???????? :puzzled:
