### ISSUE TITLE
Is there a way to return the model instead of the reform object?

### ISSUE THREAD

**Issue by magicalbanana** [apotonick/reform#214]
Because in Devise when trying to override the registratoins path or whatever it fails to find the mapping because of the object that is being returned.

**Comment by fernandes** [comment]
hey @magicalbanana,

could you please post your controller code? I do really suspect you'll need to overwrite devise controller.

ps: You should give trailblazer a try in this case

**Comment by apotonick** [comment]
@magicalbanana The solution is to set a model name for your form: https://github.com/apotonick/reform#activemodel-compliance
