### ISSUE TITLE
Question:  How to get Form class defined by collection?

### ISSUE THREAD

**Issue by speckins** [apotonick/reform#216]
I can see that reform creates an anonymous class to wrap each collection object.  Is there a (sanctioned) way to access this class for a specific collection?

(I found it on `MyFormClass.representer.representable_attrs[:definitions]["<collection_name>"][:form]`, but I can't tell if there is a better way that requires less internal knowledge of Reform::Form.)

Additionally, is there a way to retrieve the value given to the Reform::Form.model method, again for a form defined in a collection block?  (I.e., for `collection :foos { model :foobar }`, how can I know the `:foos` model is `:foobar`?)

I'm trying to use POROs with the nested_form gem (or a home-grown version thereof), and I would like to be able to automatically create a "blank" form object for the purpose of generating a template for new collection items in the form.

**Comment by apotonick** [comment]
Hey @speckins !

As far as I can remember now, this is the only way to access a collection form class. Reason for this is: until now, we didn't need a more _public_ semantic. However, if you want, we can provide a public accessor?

To answer your second question: You can use `Form::model_options` as implemented here: https://github.com/apotonick/reform/blob/master/lib/reform/form/active_model.rb#L79

**Comment by speckins** [comment]
No, I don't suppose I need a public accessor.

Thanks for the response!
