### ISSUE TITLE
nested collections and validate 

### ISSUE THREAD

**Issue by eblasco** [apotonick/reform#220]
Hi

I have a couple of nested collections as part of my Reform class like this:

class RequestForm < Reform::Form

property :title
property :abstract

 # other properties and single collection here

collection :actions, populate_if_empty: Action do
    collection :resources, populate_if_empty: ActionResource do     
      property :resource_name, writeable: false
      property :resource_id
      property :amount
      property :comments
    end

    # Another collection for documents will be here
  end

end

then my view:

 <%= form_for @request_form, :html => {:class => 'form well'} do |f| %>

<div class="row-fluid top-buffer">
        <legend>Available Resources</legend>
        <%= f.fields_for :actions do | action_builder | %>

          <%= action_builder.fields_for :resources do |resource_builder| %>
            <%= resource_builder.text_field :amount %>
            <%= resource_builder.text_field :comments %>
          <% end %>

         <% end %>

      </div>
<% end %>

The form renders well, but after submitting, the @request_form.validate(params[:request]) fails with a "wrong number of arguments 0 for 1". If I remove the nested collections (actions and its resources) the error disappears. Am I missing any step here?. This is how I call the form object in create:
@new_request_obj = Request.new
@request_form = RequestForm.new(@new_request_obj)

if @request_form.validate(params[:request]) 
 @request_form.save | nested | do
    @new_request_obj.assign_attributes(nested)
  end
end

This is how params[:request] looks like:
{"title"=>"", "abstract"=>"", "fos_attributes"=>{"0"=>{"fos_type_id"=>"", "is_primary"=>"0"}}, "roles_attributes"=>{"0"=>{"first_name"=>"", "middle_name"=>"", "last_name"=>"", "email"=>"", "position"=>"", "country"=>"", "_destroy"=>""}}, "supporting_grants_attributes"=>{"0"=>{"title"=>"supp grant title", "pi_name"=>"supp grant pi", "begin_date"=>"", "end_date"=>"", "grant_number"=>"", "subaward_number"=>"", "awarded_amount"=>"", "awarded_units"=>"", "percentage_award"=>"", "funding_agency_id"=>"", "program_officer_name"=>"", "program_officer_email"=>"", "comments"=>""}}, "actions_attributes"=>{"0"=>{"resources_attributes"=>{"0"=>{"amount"=>"34", "comments"=>""}, "1"=>{"amount"=>"", "comments"=>""}}}}}

**Comment by apotonick** [comment]
Hey, can you send me the complete stacktrace. And, this time: https://guides.github.com/features/mastering-markdown/

**Comment by fran-worley** [comment]
I'm going to close this as it's been over a year. Do reopen if you need 😄
