### ISSUE TITLE
Reform doesn't like `Boolean` attribute type using Coercion

### ISSUE THREAD

**Issue by kalleth** [apotonick/reform#226]
The readme on @solnic's `Virtus` gem (https://github.com/solnic/virtus) seems to imply that setting a property of `Boolean` is normally valid unless another library "defines another" -- see his "important note about boolean types" in the README, however, I get a NoMethodError when attempting to use it. See the following spec:

```ruby
require 'reform'
require 'reform/form/coercion'

describe "Using boolean attributes" do
  it "can be defined" do
    expect {
      class BookingForm < Reform::Form
        include Coercion
        property :yesno, type: Boolean
      end
    }.not_to raise_error
  end
end

class VirtusBooking
  include Virtus.model

  attribute :yesno, Boolean
end

describe VirtusBooking do
  it "initializes" do
    expect { VirtusBooking.new }.not_to raise_error
  end
end
```

Spoiler alert, the output is:

```
Failures:

  1) Using boolean attributes can be defined
     Failure/Error: expect {
       expected no Exception, got #<NameError: uninitialized constant BookingForm::Boolean> with backtrace:
         # ./spec/coercing_booleans_spec.rb:9:in `<class:BookingForm>'
         # ./spec/coercing_booleans_spec.rb:7:in `block (3 levels) in <top (required)>'
         # ./spec/coercing_booleans_spec.rb:6:in `block (2 levels) in <top (required)>'
     # ./spec/coercing_booleans_spec.rb:6:in `block (2 levels) in <top (required)>'
```

Note that Virtus appears to look up the Boolean constant successfully, however, so I don't think it's a clash.

Gemfile:

```ruby
source 'https://rubygems.org'

gem 'rspec'
gem 'virtus'
gem 'reform'
```

I suspect, but am not certain, that this relates to this issue on Virtus: https://github.com/solnic/virtus/issues/55

**Comment by kalleth** [comment]
Using `Virtus::Attribute::Boolean` rather than `Boolean` fixes this, btw.

**Comment by solnic** [comment]
``` ruby
class Reform::Form
  include Virtus::ConstMissingExtensions
end
```

??? helps ????

**Comment by kalleth** [comment]
@solnic yup, that added line causes the test to pass with just `type: Boolean` :)

**Comment by apotonick** [comment]
So should we include `Virtus::ConstMissingExtensions` when including `Reform::Coercion`?

**Comment by kalleth** [comment]
Wouldn't that be better off pushed down to a responsibility of `Representable::Coercion` ? It seems to me (without detailed knowledge of the codebases) that that class is responsible for virtus-level interaction (see: https://github.com/apotonick/representable/blob/master/lib/representable/coercion.rb).

If that gem (which is a dependency of Reform) already depends on Virtus, then it feels like that's the appropriate place to handle it, as it'll fix other clients of Representable.

Further, wouldn't this allow simplification of the README.md on Reform? No need to include Virtus explicitly in the Gemfile as the API to use it is abstracted via the `type:` attribute here.

**Comment by apotonick** [comment]
Absolutely true, @kalleth! However, Virtus is not a static dependency in Representable, so you still need to add it to your Gemfile manually.

**Comment by kalleth** [comment]
:+1: Thanks for the guidance, @apotonick. I'm not sure of the implications of adding that extra include in `representable`, so do you mind if I leave this in your hands now rather than submitting a PR?

**Comment by apotonick** [comment]
Absolutely, my friend. 

[img]: https://i.chzbgr.com/maxW500/4614403072/h0242FEB6/

**Comment by apotonick** [comment]
I am trying to trigger `Virtus::ConstMissingExtensions` but it seems that the constant `Boolean` is already defined and virtus doesn't get involved in resolving.

If I change that line https://github.com/apotonick/representable/blob/master/test/coercion_test.rb#L16 to 

```ruby
property :ok, :type => Boolean
```

it still works (no constant missing exception), even though the coercion doesn't happen.

**Comment by fran-worley** [comment]
I'm going to close this now as the project has moved from Virtus to Dry-Types.
