### ISSUE TITLE
How to test validations in Reform::Contract with custom I18n translation keys?

### ISSUE THREAD

**Issue by sauy7** [apotonick/reform#227]
Inside a contract block with a Trailblazer::Operation I need to use as custom translation key to replace ActiveModel's errors.messages.inclusion:

    class Thing < ActiveRecord::Base
      class Create < Trailblazer::Operation
        ...
        contract do
          property :attr
          validates :attr, inclusion: { in: %w(...), message: I18n.t("errors.messages.custom_key") }
        end
      end
    end

The key is specified in my Rail's projects config/locales/*.yml files.

This works fine when running the application for real and during integration testing but in the concept test I get a translation missing error:

    class ThingCrudTest < MiniTest::Spec
      describe "Create" do
        it "invalid attr" do
          res, op = Thing::Create.run(user: { attr: 'invalid_attr' } )

          puts op.errors # => role=>["translation missing: en.errors.messages.custom_key"]
          op.errors.to_s.must_equal "{:attr=>[\"custom error message\"]}” # fails
        end
      end
    end

Perhaps I need to add something to the test or the contract block?

**Comment by apotonick** [comment]
Sounds like we have to enable something in the concept tests, then. Does the problem occur when you run `bundle exec rake` or only when you run the concept test in isolation?

**Comment by sauy7** [comment]
when running rake

**Comment by sauy7** [comment]
Some findings...

1. It seems that the I18n.load_path only includes the config/locales/*.yml files after the Rails app has been initialized. These files don't exist in the load path when the contract in the crud.rb file is processed.

2. I very much doubt this is the correct way to go about this, but adding the following to Trailblazer::Railtie seems to solve this issue:

    initializer 'trailblazer.add_locales' do |app|
      require 'active_support/i18n'
      I18n.load_path += Dir[File.expand_path('config/locales/*.yml', app.root)]
    end

I doubt this is correct because it leads to the creation of duplicate entries in the I18n.load_path later on.

3.Alternatively, the following line can be added to the top of the relevant crud.rb or crud_test.rb file:

I18n.load_path += Dir[File.expand_path('config/locales/*.yml', Rails.root)]

again with later duplication in the load path.

4. Converting the test from:

    class ThingCrudTest < MiniTest::Spec

to:

    class ThingCrudTest < ActiveSupport::Testcase

does not work.

**Comment by sauy7** [comment]
Running the latest code as of today and this issue seems to be resolved.
