### ISSUE TITLE
supress errors details 

### ISSUE THREAD

**Issue by gogainda** [apotonick/reform#228]
Hello! I am using active_model-errors_details to supress i18n on errors of a model. It works great with simple model but does not with reform. Why errors.details is still i18n'ed?

**Comment by apotonick** [comment]
Sorry I have no idea about `active_model-errors_details` and what it does. A bit of explanation would help. How do you normally use it?

**Comment by gogainda** [comment]
form has errors method  which returns i18ned error messages. Error details should return not i18ned error messages, it is very useful if you implement i18n on client side. So along with errors I return errors_details like {errors: user.errors, errors_details: user.errors.details }. Normally, user.errors.details are not translated, just keys, but with reform they get translated, I am not sure why.

**Comment by fran-worley** [comment]
As of Reform 2.2 all active model / active record related code has moved to the reform-rails gem.

If you're still experiencing this issue, please can you reopen it in the correct gem. Thanks 😺
