### ISSUE TITLE
Handling coercion failures

### ISSUE THREAD

**Issue by jorge-marques** [apotonick/reform#229]
Hello,
I'm using the Coercion module to coerce a string to a DateTime object. 
It mostly functions as expected, however, when the coercion fails, the field is simply set to nil. 
Is there a way to add an error to the form object and let the user know the input string is invalid?

**Comment by apotonick** [comment]
Good one, this sounds like a missing function. Thanks Jorge, I will soon look into that.

**Comment by fran-worley** [comment]
This works when using dry-validations. See example here:
https://github.com/apotonick/reform/blob/master/test/validation/dry_validation_test.rb#L46-L48

This example is with a boolean field, but the point stands we get a message that the format was incorrect, and not that the input was missing. 

I'm therefore closing this. If you need this to work with AM-V you'll need to open an issue in Reform-rails. Feel free to re-open if I've missed something :)
