### ISSUE TITLE
Add documentation to "Dirty Tracker" that "changed?" does not play nicely with boolean fields/properties unless you use coercion

### ISSUE THREAD

**Issue by AndrewSwerlick** [apotonick/reform#232]
I've got a form with a collection of object, each one of which has a boolean property. I'm finding that reform always reports changed?(:boolean_prop) as true for any of the nested items. In debugging I identified that the issue is in `Form::Validate::Changed#call` specfically

    form.changed[name] = form.send(name) != fragment

The problem is that `form.send(name)` returns `true` and `fragment` returns `1`

I was able to get around this by using coercion, but my brain didn't immediately realize the problem was due to a type mismatch. I had to open up pry and start debugging before I made the connection. It might be worth adding something to the Dirty tracking section highlighting that booleans (and I'm guessing date times) will need to be coerced for dirty tracking to work.

**Comment by apotonick** [comment]
Hmmmmmm... hmmm.... hmm... In your case, I don't really understand the problem, though. How is the form supposed to know that "1" means `true` in your data model?

The same with dates (good point, thanks for pointing that out!!! :heart_eyes_cat: ) - Coercion should be a Reform/Disposable thing and not be deferred to ActiveRecord, anyway. Maybe we should add that to the README?

We have to make clear that Reform and Disposable don't know about what ActiveRecord coerces behind its manly back - that's what you're asking for, right?

**Comment by AndrewSwerlick** [comment]
Yeah basically. I understood why it didn't work very quickly once I started debugging, but it didn't occur to me naturally. I think it's just one of those areas of rails black magic you forget is happening at all, so it's worth calling out in the documentation as a reminder. Even if it had just been a sentence reminding me that unless you use coercion, the value coming from a http post will always be "1", while the value from the database will be true, I wouldn't have scratched my head for quite as long.

**Comment by AndrewSwerlick** [comment]
Note the reason why my report reads kind of weird, starting out like I'm describing a code bug rather that a documentation issue, is because I legitimately thought this was a bug at first. That's how consued

**Comment by apotonick** [comment]
Thanks again for finding this - I moved coercion to Disposable and now everything is as you expected it to work.

1. Coerce value
2. Assign value
3. Compare and decide changed?
