### ISSUE TITLE
How to handle an item in a collection that might not be in the parameters?

### ISSUE THREAD

**Issue by AndrewSwerlick** [apotonick/reform#235]
I have a form with a nested collection. When I render this form object, some of the items in the collection do not get associated html controls because they are in a state where editing is a valid business option. However we still need to render them for reading.

Because there are no html controls, the params posted back don't include references to this collection items. As a result, the form collection property has more items than there are parameter hashes. This understandably causes all kinds of issues as reform assigns the posted parameters to the wrong collection objects.

In short I have a mismatch between the object graph created by the form object and the object graph of parameters being posted back. I don't see anyway in the documentation to fix this problem. As far as I can tell `populate_if_empty` and `populator` are only appropriate if I have the opposite problem, more items in my parameters than the form object collection. Is there a method where I can tell reform how to match a parameter fragment to a specific collection item?

For now I've worked around the issue by adding hidden field controls for all the read-only items, but that feels hacky.

**Comment by apotonick** [comment]
Hey Andrew,

you are right, populators are only for mapping incoming fragments to nested forms. You need to change your populator so it is able to find the correct nested form by `id` (or whatever you use for IDing objects).

While I decided to include that into Reform per default, I'll give you an idea of what you need to do.

```ruby
collection :songs, populator: :populate_song! do
  # ..
end

def populate_song!(fragment, *)
  existing_song = songs.find { |s| s.id.to_s == fragment["id"] } 
  return existing_song if existing_song

  songs << Song.new # other case, incoming fragment doesn't match.
end
```

It's pretty cool, the populator let's you solve this problem in a very generic way. As I said, I will allow that with a macro so you don't need to code every time you want to match fragments by id, and not by order.

**Comment by apotonick** [comment]
Oh, BTW, this is Reform 2, so make sure to use my reform-2 branch. I'll release Reform-2.0.0 in 1-2 weeks.

**Comment by fran-worley** [comment]
Hi Andrew,

I'm going to close this as it's been added to Reform 2. 😄
