### ISSUE TITLE
Calling #valid? on form object adds duplicate messages to errors array

### ISSUE THREAD

**Issue by npearson72** [apotonick/reform#241]
```
=> {:name=>["can't be blank", "can't be blank", "can't be blank"],
 :quantity=>
  ["must be greater than or equal to 1000",
   "must be greater than or equal to 1000",
   "must be greater than or equal to 1000"]}
```
Each time I call form#valid? reform pushes a duplicate into the array. Is this by design for some reason?

**Comment by apotonick** [comment]
Yes! `#valid?` is not a documented public method. You should use a contract and `#validate` or validate with an empty hash, but the `validate` method isn't designed to be run multiple times, too.

Looking into the code, I see why and should probably fix it :grin: ...

**Comment by npearson72** [comment]
Cool, thanks for the reply. This doesn't happen with Lotus by the way, only with AV.
