### ISSUE TITLE
Default error messages with Lotus?

### ISSUE THREAD

**Issue by npearson72** [apotonick/reform#242]
I noticed your post here: https://github.com/lotus/validations/issues/67

Is there a way in reform to get a similar output to what rails offers with `errors.full_messages` when using lotus?

**Comment by apotonick** [comment]
Once I implemented it in Lotus, yeah! :smile:

**Comment by npearson72** [comment]
Oh, you already implemented it? :-) How do I access it?

**Comment by apotonick** [comment]
Read the above as "once I implemented it in Lotus, I'll let you access it". I prototype here: https://github.com/trailblazer/lotus-validations

**Comment by npearson72** [comment]
Ah, cool. I'll play with this fork. Thanks!
