### ISSUE TITLE
Help with complex nested form and validations

### ISSUE THREAD

**Issue by npearson72** [apotonick/reform#243]
Sorry for posting so many issues/questions, but I recently discovered your excellent gem and am hoping it can help me replace my own similar (but less sophisticated implementation).

With basic objects, all of this is pretty easy. But I have the following complex scenario:

I am building a shopping cart with Products. A Products has many Variants, which are its children, making the product a parent.

Now a Product can have feature combinations like: `Color=Red, Size=Small`

**This Product's Variants require:**

A) Must have feature keys (i.e. `Color, Size`) that the parent has
B) The feature key/value combinations must be different from the parent. So in this case, the variant can't have `Color=Red, Size=Small`. But `Color=Blue, Size=Large` is ok.
C) The feature key/value combinations must also be different from other Variants (i.e. siblings)

My current implementation uses custom validation mappings across a series of service objects that I roll up into a larger service object that tries to manage and delegate all of these concerns.

My hope is that reform can replace a lot of this for me, but I'm confused on how to include nested validations for my case.

PS: I'm also using the lotus validations because I hope to be able to flatten the nested errors.

I can provide more detail if you like, but would first like to know if this is something you can help me get a handle on. Thanks.

**Comment by apotonick** [comment]
You can nest forms, e.g.

```ruby
class ProductForm < Reform::Form
  collection :variants do
    property :size
  end

  validate do
    variants.each do |v|
      v.size == "Small" or errors.add("so", "wrong")
    end
  end
end

product.variants #=> [<Variant size="Small">, ...]
form = ProductForm.new(product)
form.variants[0].size #=> "Small"
```

A nested form is simply an object graph with Ruby API and you can use it for complex validations, etc. I recommend reading the _Nested Forms_ and _Mastering Forms_ chapters of the Trailblazer book, they discuss this!

**Comment by npearson72** [comment]
The `#validate` method is what I needed! This is great, thank you!
