### ISSUE TITLE
broken of validates_xxx_of 

### ISSUE THREAD

**Issue by niedhui** [apotonick/reform#247]
Hi, after upgrade reform from 2.0.0.rc1 to 2.0.0 , the active_model's validations help methods dose not work, like `validates_numericality_of`, `validates_length_of`. in Reform::Form::ActiveModel,  only some basic mehtods were delegate to the Validator which include `ActiveModel::Validations`, but the `validates_xxx_of` are not.  Will they come back ?

I add an initializer file to fix it in our code 
```ruby
Reform::Form.instance_eval do
  class << self
    delegates :validator, :validates_absence_of, :validates_acceptance_of, :validates_confirmation_of,
                          :validates_exclusion_of, :validates_format_of, :validates_inclusion_of, :validates_length_of,
                          :validates_size_of, :validates_numericality_of, :validates_presence_of
  end
end
```

**Comment by apotonick** [comment]
They are still there, but  we don't include `ActiveModel::Validations` into the form itself anymore and only delegate their DSL.

Here is where this is done: https://github.com/apotonick/reform/blob/master/lib/reform/form/active_model/validations.rb#L24

You can add your delegations there, if you want and I merge it. But before that, I'd like to know, why do you use this form and not the `validates validator: ..` form?

**Comment by niedhui** [comment]
legacy codes.... when rails introduce the new `validates` way, they did not deprecate the `validates_xx_of`, so we keep it, and move it from model the reform. I think i will change my code to the `validates` form, and using my own initializer file as a workaround for now. thanks. 
and I think  we should metion this in the CHANGES.md

**Comment by apotonick** [comment]
Maybe you're right!
