### ISSUE TITLE
broken of save with block

### ISSUE THREAD

**Issue by niedhui** [apotonick/reform#249]
codes from README
```ruby
 @form.save do |hash|
    album = @form.model
    album.update_attributes(hash[:album])
  end
```
before 2_0, it works, the `hash` is `ActiveSupport::HashWithIndifferentAccess`. and now, the  `hash` is just a plain hash with string keys. we can only access it using `hash['album']`. Will this change back to the `AS::HWIA` style or  fix the README(and my codes~).
And I did not read the `disposable` codes, is it safe to just using the string keys, or I should cast the hash myself.

but when using composition, the hash will be `{:symbol_key => {"string_key" => "value"}}`， a litte 'not-unifiable-interface'

**Comment by gertfj** [comment]
+1 for this, I have currently changed my code from:

```ruby
form.save do |hash|
  result = Model.create_model!(user: current_user, data: hash)
end
```

to

```ruby
form.save do |hash|
  result = Model.create_model!(user: current_user, data: hash.with_indifferent_access)
end
```

but it would be nice not having to remember doing that.

**Comment by apotonick** [comment]
We could add the `.with_indifferent_access` but then only in `Form::ActiveRecord` forms. I stripped all the Rails-specific code from Reform in 2.0 and it feels great. So, we can re-introduce this but only for Rails forms.

**Comment by gertfj** [comment]
Would be great, habits form quickly and I'm certain that I will forget to add it later.

**Comment by apotonick** [comment]
Pull requests highly appreciated. I don't use `#save` with block so it might take a while. :wink:
