### ISSUE TITLE
Nilify blanks

### ISSUE THREAD

**Issue by michaelimstepf** [apotonick/reform#251]
Awesome gem, thanks!

Is there any way to nilify blank strings "" similar to https://github.com/rubiety/nilify_blanks or https://github.com/solnic/virtus#nullify-blank-strings-mode

**Comment by apotonick** [comment]
This would go into Disposable and expose the following semantics.

```ruby
class AlbumTwin < Disposable::Twin
  property :title, nullify: true
end

twin.title = ""
twin.title #=> nil
```

Is that what you're after?

**Comment by michaelimstepf** [comment]
Yep, thanks!

**Comment by apotonick** [comment]
Wait wait wait, we still need to implement this. :wink: 

So, this only gets invoked when the incoming value is `""` (blank string)? What should happen when coercion is enabled, too? Nullify wins over coercion?

**Comment by michaelimstepf** [comment]
Yes, only for blank strings. Nullify should win over coercion I think.

**Comment by olavolav** [comment]
+1 Would be great

**Comment by fran-worley** [comment]
Looks like this finally happened 🎆 🎉 http://trailblazer.to/gems/disposable/api.html#nilify
