### ISSUE TITLE
Clarify documentation for `model :name`

### ISSUE THREAD

**Issue by brightbits** [apotonick/reform#255]
I was confused and thought I had to define `model :name` once for each model, this caused it to use the last one for the form url and params. We should allow to only be called once to help avoid this confusion as well as updating the documentation

**Comment by apotonick** [comment]
Allowing this only once is very railsy (we've all seen `DoubleRenderError`, haven't we?) and will unnecessarily restrict users that _want_ to override and old `::model` setting, e.g. when defining it once in a base class and then overriding with a module or in a subclass.

```ruby
class SongForm < Reform::Form
  model :song

class HitForm < SongForm
  model :hit # would raise exception.
```

Thanks, I added some docs: https://github.com/apotonick/reform#activemodel-compliance
