### ISSUE TITLE
A bug with confirmation?

### ISSUE THREAD

**Issue by JustMikey** [apotonick/reform#257]
I have a form like this and the thing is, it always fails `password_confirmation` whether it's actually present or not as long as there is `confirmation: true` in the password validation. Is it a bug or I miss something?

    class UserForm < Reform::Form

    properties :email, :password

    property :password_confirmation, virtual: true

    validates :email,
            presence:     true,
            format:       {with: /\w+\@\w+\.\w+/},
            length:       {minimum: 5, maximum: 100}

    validates_uniqueness_of :email

    validates :password,
            presence:    true,
            length:       {minimum: 8},
            confirmation: true

    validates :password_confirmation,
            presence: true

    end

**Comment by apotonick** [comment]
I have never used the `confirmation: true` validator, but I suppose it is not designed to work with a form object and somewhere writes to the "model" which is actually a form. 

The Rails validators do that a lot and this is wrong and gives me a hard time in Reform. Best is not to use them.

Check out the `ConfirmationValidator` in ActiveModel and what it actually does. I bet a sixpack on it that it does `model.password_confirmation = nil` somewhere. What's this validator's job?

My suggestion is not to use it. Here's how we do it in the Trailblazer sample app: https://github.com/apotonick/gemgem-trbrb/blob/chapter-9-tyrant/app/concepts/session/operations.rb#L90

**Comment by JustMikey** [comment]
I see, thank you for the answer and quick reply

**Comment by apotonick** [comment]
I'd love to hear what you found out about the iniquities of this particular validator!

**Comment by townhouse** [comment]
I ran into this issue and in the end went with the solution in the Trailblazer sample app which works well.

It looks like ConfirmationValidator creates a virtual attribute on the model, in this case #password_confirmation then compares it to the actual value of #password - but it only does this comparison if #password_confirmation is not nil.

**Comment by apotonick** [comment]
I added a note here: http://trailblazerb.org/gems/reform/validation.html It simply says people shouldn't use `confirm: true` as it does Rails magic and writes on the model, and that we don't appreciate that.
