### ISSUE TITLE
Does skip_if and prepopulator work together?

### ISSUE THREAD

**Issue by FelipeKoblinger** [apotonick/reform#259]
Hello! :)
I don't know if this is a bug or not, but, when I use a `prepopulator` with `skip_if` option in a collection, the prepopulated object do not get skipped by `skip_if` condition, it saves an empty model in database.

``` ruby
collection :phones, skip_if: lambda { |phone, *| phone['phone_number'].blank? },
           prepopulator: -> (*) { self.phones << Phone.new if self.phones.empty? },
           populate_if_empty: Phone do
  property :phone_number
  property :phone_type
end
```

Reform version:  2.0.1 (commit: 38f30b2d5c99740105922c36881811b3bd1f378e)
Rails version: 4.2.3

Is something I'm doing wrong or is normal?

* Also tried with `skip_if: :all_blank`

Thanks :)

**Comment by apotonick** [comment]
Hey, `:skip_if` is only considered in `#validate`, which is usually called _after_ `#prepopulate!`. Also, since `#prepopulate!` doesn't receive the params hash, there's no way how `:skip_if` could be reused.

Keep in mind that in prepopulators you can add any logic you want, e.g. `if phones.empty`.

**Comment by apotonick** [comment]
Ah, I just reread, maybe you shouldn't call `form.prepopulate!` in the validating/persisting request? This is only meant to be used for rendering the form.

The _Nested Forms_ chapter in the Trb book talks about this in great detail. :stuck_out_tongue_winking_eye:

**Comment by FelipeKoblinger** [comment]
Ya! Worked! My mistake :sweat_smile: 
Thanks, @apotonick :+1:
