### ISSUE TITLE
Reform 2.0 breaks Rails "confirmation: true" validation

### ISSUE THREAD

**Issue by gertfj** [apotonick/reform#265]
The follwing code works with Reform 1.2.6 but in Reform 2.0.1 the forms ```password_confirmation``` is always ```nil```.

```ruby
validates :password, presence: true, length: ::Devise.password_length, confirmation: true}
```

**Comment by apotonick** [comment]
Discussed here: https://github.com/apotonick/reform/issues/257
The title should be "Rails confirm validator breaks Reform" ;)
