### ISSUE TITLE
Problem with batch updating nested collections

### ISSUE THREAD

**Issue by tolhaje** [apotonick/reform#266]
Hey, I've got a problem with updating nested collections. Let's say I've got a form object for User model, and user has many photos (Photo model).
```ruby
form.photos
=> [#<Photo:0x007f9ea2494d58
  id: 1,
  image: "whatever.jpg",
  description: "whatever photo"]
 #<Photo:0x007f9ea2494bc8
  id: 2,
  image: "whatever2.jpg",
  description: "whatever 2 photo"]
```
then, let's say I want to batch update descriptions of those photos. Params look like this:
```ruby
params
=> {"photos"=>[{"id"=>"1", "description"=>"new whatever photo"}, {"id"=>"2", "caption"=>"new whatever 2 photo"}]}
```
And then it's okay. But when params looks like this (they're not ordered by id):
```ruby
params
=> {"photos"=>[{"id"=>"2", "description"=>"new whatever 2 photo"}, {"id"=>"1", "caption"=>"new whatever photo"}]}
```
Reform (or maybe rather disposable, hadn't had time to investigate) just assigns first element of params photos array to first element from `form.photos` array. It doesn't care about id. Not sure if bug or feature, so let me know :wink:

**Comment by apotonick** [comment]
It's a feature. Reform per default does populate by position, if you want to populate by a field like `:id` you need to write your own populator. Reform doesn't know anything about IDs or special semantics of fields.

This is documented in the _Authentication_ chapter of the Trailblazer book. This chapter is out in a few days. Basically, it would go like this.

```ruby
collection :photos, populator: ->(fragment, options) { photos.find { |p| p.id == fragment["id"] } or photos << Photo.new }
```
