### ISSUE TITLE
On form error, simple_form association helpers are not filled

### ISSUE THREAD

**Issue by acaron** [apotonick/reform#270]
I use the following initializer to make association work (as proposed here: https://github.com/apotonick/reform/issues/122):

```ruby
# /config/initializers/reform.rb
Reform::Form::ModelReflections.module_eval do
	# TODO: This is a hack for making simple_form association inputs work with reform.
	# This should be removed once the problem is fixed in the gems.
	def self.included(base)
		def base.reflect_on_association(*args)
			model_name.to_s.constantize.reflect_on_association(*args)
		end

		super
	end
end

# Form.rb
class Form < Reform::Form
	include ModelReflections
end
```

And this code for my association:

```ruby
# ClientForm.rb
class ClientForm < Form
	model :client

	properties :name, :language_ids
end

# _form.html.erb
<%= f.association :languages, as: :check_boxes, collection: Language.all, disabled: [default_language.id] %>
```

But on error, the content just disappear. If there's no error, it saves normally and everything is fine!

![Before](http://i.imgur.com/hvlb60s.png)

![After](http://i.imgur.com/Ts91sn1.png)

I use Rails 4.2.3, Simple Form 3.1.0 and Reform 2.0.1. Does someone have an idea what is happening?

**Comment by apotonick** [comment]
Oh no, more ActiveModel sadness :cry: .. when you say "content just disappears", what exactly do you mean?

Also, would you be willing to help me writing a few tests in the bundled test app (`test/rails4.2`)? :grimacing:

**Comment by acaron** [comment]
Sure for the tests, I'll look into it!

The `params` hash contains `language_ids` and the model attribute contains the old `language_ids` (what's in the database). The checkboxes are not checked for whatever reason... I can dig into the code further tomorrow to check where it comes from!

**Comment by apotonick** [comment]
So the boxes are not checked in case of invalid input, is that the problem?

**Comment by acaron** [comment]
Exactly

**Comment by apotonick** [comment]
Can you, in the form view, add `@form.language_ids.inspect` and paste what this is in invalid state?

**Comment by acaron** [comment]
It output: `[""]`

**Comment by spectator** [comment]
W/o that hack you mentioned, this should work just fine, however there is a whole set of other related issues so it depends what else you do with `language_ids`

```ruby
class ClientForm < Reform::Form
  include Reform::Form::Coercion
  property :language_ids, type: Array[Integer]
end
```

```erb
= f.language_ids, as: :check_boxes, collection: Language.all
```

Not sure if this ever be working with SimpleForm and Reform because of too much AR magic.

**Comment by acaron** [comment]
If I remove the hack and try the way you said, it still doesn't work. With SimpleForm, the field is set this way:
`= f.input :language_ids, as: :check_boxes, collection: Language.all`

**Comment by coatezy** [comment]
Hey, I'm also experiencing the same issue as @acaron. Only seems to be a problem with check_boxes. radio_buttons and multiselect both work as expected.

**Comment by spectator** [comment]
@acaron @coatezy  Would be great if you could create a simple app to demonstrate this issue.

**Comment by coatezy** [comment]
@spectator Hey, I'm throwing something together now.

**Comment by coatezy** [comment]
Hey, 

Below is a demo on Heroku and the repo. Hope it helps. 

https://fathomless-gorge-7498.herokuapp.com/
https://github.com/coatezy/reform_demo

**Comment by spectator** [comment]
https://github.com/coatezy/reform_demo/pull/1

@coatezy I sent PR to your demo app, check it out
@acaron you might want to take a look at this too

**Comment by apotonick** [comment]
We can try to support `association` from simple_form in a separate `SimpleForm` module in Reform, as the fix looks kinda tedious. Also, we can speak to the simple_form team and try to solve this on that level.

**Comment by acaron** [comment]
A bit late (I was on vacation on August 11th) but the herokuapp is demonstrating my issue! Thanks @coatezy

**Comment by acaron** [comment]
Quick fix: add `checked: @form.language_ids` to form input. Also, doesn't work with virtual attribute too. You must set `checked`manually. Can you add that to your test app @coatezy ?

**Comment by fran-worley** [comment]
As of Reform 2.2 all active model / active record related code has moved to the reform-rails gem.

If anyone is keen to try and add support for SimpleForm Associations, feel free to raise a PR to include a SimpleForm module in reform-rails.

I'm closing this as no more work will be done here to support SimpleForm, but feel free to reopen in reform-rails if you're still experiencing this issue. Thanks 😺
