### ISSUE TITLE
How do you handle property-less collections?

### ISSUE THREAD

**Issue by AndrewSwerlick** [apotonick/reform#274]
I have a form that lets users add "Roles" to "Users". The User `has_many :roles` and the idea is that users can check boxes next to each role. However they can't edit anything about the role itself, so it's not a true nested form. What's the most idiomatic reform way to handle this. I could create a virtual property and manually loop through the results with coercion, but I wasn't sure if there was a collection driven way to handle this.

**Comment by apotonick** [comment]
You can simply have a `collection`, literally! :wink: 

```ruby
class AlbumForm < Reform::Form
  collection :roles
end
```

This will treat `model.roles` as an array but each item as a scalar value, not a "real" object. Is that what you want?

**Comment by AndrewSwerlick** [comment]
Partly, what I didn't make clear, is I was wondering if there's anything reform does to remain backwards compatible with how rails form builders treat this sort of relationship, like it does for nested forms. So generally rails forms will have a bunch of fields with a name like `user[roles_ids][]` and that automatically get's converted to a collection of roles.

I have it working in my form with something like this

    property :role_ids, from: :roles

   def role_ids=(value)
     super Role.where(id: value.map(&:to_i))
  end

This works fine, and appropriately sets the value of the has_many collection when `sync` is called, but I was curious if I was manually replicating something reform already handled more idiomatically.

**Comment by apotonick** [comment]
Ah interesting - we _could_ provide that functionality in Reform or in Disposable, maybe in a separate module `CollectionIDs` or something.

I didn't know that the associations stuff does internally work with `xxx_ids=`.

**Comment by AndrewSwerlick** [comment]
yeah, it might ease the transition from working directly with active record. At the least, there should probably be something in the documentation that suggests am "officially recommended" way to handle. Maybe a section on reform migration potential gotchas for people used to working directly with active record. I assume the way I'm handling it would be considered the most idiomatic approach in reform to date?

**Comment by apotonick** [comment]
What UI element(s) do you use when rendering this kind of collection?

**Comment by AndrewSwerlick** [comment]
Checkboxes generally. So each box looks like 

`<input type=checkbox name=user[role_ids][] value=2 />`

If I have a long list of options, I've hacked together a multi-select control with some javascript that ends up a series of hidden fields, one for each item that's been selected, so like this.

`<input type=hidden name=user[role_ids][] value=2 />`

**Comment by fran-worley** [comment]
As of Reform 2.2 all active record/ Active model related code was moved to the reform-rails gem.

I'll be closing this as no further changes will be made to Reform to support this case. Feel free to open a new issue in [reform-rails](https://github.com/trailblazer/reform-rails). 

If you want to help improve the docs, feel free to raise a PR on the [sites repository](https://github.com/trailblazer/trailblazer.github.io).
