### ISSUE TITLE
Ability to validate only attributes passed to update and ignore the rest

### ISSUE THREAD

**Issue by pbrudny** [apotonick/reform#276]
I want to validate attributes passed to update without a need to fetch the existing record. 
Right now I don't see any obvious way to do it with Reform. 

However some people suggests this is the right tool
https://twitter.com/joshuapaling/status/538169606876057600

Am I missing something?

**Comment by apotonick** [comment]
Reform tracks what properties changed in `#validate` and you could use that in your validators.

```ruby
form.changed?(:title) #=> false
form.validate(title: "Greatest Hits")
form.changed?(:title) #=> true
```

You can test that in the validation.

```ruby
class AlbumForm < Reform::Form
  property :title
  validate :title do
    return unless changed?(:title)
    # your validation here
  end
```

Is that helpful?

**Comment by apotonick** [comment]
Oh, and since we drop support for `ActiveModel::Validations` pretty soon we have all kinds of possibilities to make this easier for "formal" validations, e.g. we could provide something like this.

```ruby
validate :title, presence: true, if_changed: true
```

**Comment by apotonick** [comment]
Oh, and I just reread your question and realised you want something else haha. :laughing: 

I don't understand why you don't want to "fetch the existing record", but you can pass nil objects into the form and make all properties `:virtual`. The _Authentication_ chapter of the Trailblazer book talks about "modelless forms".

**Comment by pbrudny** [comment]
Thanks for quick response. Both ideas don't fully work for me.
```ruby
validate :title do
    return unless changed?(:title)
```
The result is `LocalJumpError: unexpected return`

and the second solution still runs validation an all fields.

However your suggestions led me to working solution which is

```ruby       
validates :title,  presence: true, if: -> { changed?(:title) }
```
