### ISSUE TITLE
How to make nested attributes mandatory?

### ISSUE THREAD

**Issue by bethesque** [apotonick/reform#278]
How do you make a nested property mandatory? In the following example, we cannot get the child validation to fail.

```ruby
require 'rails' # Rails 4
require 'reform' # Reform 2.0.1

Parent = Struct.new(:name, :child)
Child = Struct.new(:name)

class ParentForm < Reform::Form

  property :name, validates: {presence: true}

  property :child do
    property :name, validates: {presence: true}
  end

end

params = {name: 'Parent', child_attributes: {name: nil}}
parent = Parent.new(child: Child.new)
parent_form = ParentForm.new(parent)
puts parent_form.validate(params) # This comes back true
puts parent_form.errors.full_messages # No errors!
parent_form.sync
puts parent
puts parent.child
```

**Comment by apotonick** [comment]
You have to do as follows.

```ruby
class ParentForm < Reform::Form
  # ..
  validates :child, presence: true
```

I am introducing a completely new validation semantic in Reform 2.1. This is mainly possible because I drop ActiveModel::Validations support in favor of the much simpler Lotus::Validations implementation (both still work, but I won't work on AM anymore). 

On top of that, I will provide cascaded validations and constraints. This will hopefully put an end to the super primitive validations we have in Rails presently without any chaining or dependency semantics.

**Comment by bethesque** [comment]
Still no love.

```ruby
require 'rails' # Rails 4
require 'reform' # Reform 2.0.1

Parent = Struct.new(:name, :child)
Child = Struct.new(:name)

class ParentForm < Reform::Form

  property :name, validates: {presence: true}

  property :child, validates: {presence: true} do
    property :name, validates: {presence: true}
  end

end

params = {name: 'Parent', child_attributes: {name: 'Child'}}
parent = Parent.new
parent.child = Child.new
parent_form = ParentForm.new(parent)
puts parent_form.validate(params) # false
puts parent_form.errors.full_messages # Child name can't be blank
```

Now it thinks that child name is blank when it isn't!

**Comment by apotonick** [comment]
The problem is `child_attributes:`, this should either read `child:` or you have to include `Reform::Form::ActiveModel` into your form so it "understands" the Rails hack. In a normal environment, there's no such thing as `*_attributes` (that's Rails form helpers, :sigh:). :grimacing:

**Comment by bethesque** [comment]
But you wrote this for Rails :P

Still can't get it working!

```ruby
require 'rails' # Rails 4
require 'reform' # Reform 2.0.1
require 'reform/form/active_model'

Parent = Struct.new(:name, :child)
Child = Struct.new(:name)

class ParentForm < Reform::Form

  include Reform::Form::ActiveModel

  property :name, validates: {presence: true}

  property :child, validates: {presence: true} do
    include Reform::Form::ActiveModel
    property :name, validates: {presence: true}

  end

end

params = {name: 'Parent', child_attributes: {name: 'Child'}}
parent = Parent.new
parent.child = Child.new
parent_form = ParentForm.new(parent)
puts parent_form.validate(params) # Still! false
puts parent_form.errors.full_messages # Still! Child name can't be blank


```

**Comment by bethesque** [comment]
Ok, got it working. Firstly, needed to upgrade from reform 2.0.1 to 2.0.3 (using 2.0.1 gave the error `private method `binding' called for {}:Hash`) . Secondly, needed to use string parameter keys, not symbol parameter keys.

```ruby
require 'rails' # Rails 4
require 'reform' # Reform 2.0.3

Parent = Struct.new(:name, :child)
Child = Struct.new(:name)

class ParentForm < Reform::Form

  include  Reform::Form::ActiveModel

  property :name, validates: {presence: true}

  property :child do
    property :name, validates: {presence: true}
  end
end

params = {'name' => 'Parent', 'child_attributes' => {'name' => 'Child'}}
parent = Parent.new
parent.child = Child.new
parent_form = ParentForm.new(parent)
puts parent_form.validate(params) # true!!!
puts parent_form.errors.full_messages # empty!!!
```

**Comment by bethesque** [comment]
Was using the form_builder_test to try and work out what was going wrong https://github.com/apotonick/reform/blob/3ffb693ff475b42f1baf36bd0a290687bf88dfe8/test/form_builder_test.rb 

I'm interested to know what this "feature" thing is? What is a "feature" compared to an "include"? Couldn't find any method definitions in the Reform codebase.

**Comment by apotonick** [comment]
I can't tell you how much I hate "hash with indifferent access" - another villainy of Rails.

The `feature` call will include the module and then register it to include it automatically in nested forms that are generated at compile time: https://github.com/apotonick/disposable#features

**Comment by jasiek** [comment]
Hey, what are your thoughts re permitting params with symbols as keys? Supporting that would mean adding a call to `.stringify_keys` somewhere within reform.
