### ISSUE TITLE
Update existing models instead of creating new ones.

### ISSUE THREAD

**Issue by tokenvolt** [apotonick/reform#281]
I am using Reform 2.0.2 with Rails 4.1.6 and I have deeply nested form.

I'm omitting most of the attributes and validations for brevity.
````ruby
class ProfileForm < Reform::Form
  property :email

  collection :jobs, populate_if_empty: ::Job, form: ProfileForms::Job
end
````

````ruby
class ProfileForms::Job < Reform::Form
  property :company, populate_if_empty: ::Company, form: ProfileForms::Company
  property :title
end
````

````ruby
class ProfileForms::Company < Reform::Form
  property :title
end
````

When I create new profile with this form - it works good. But my question is how do I update existing model, so it does not create new job or company every time #save is called? In Rails accepts_nested_attributes_for takes care for this, but how do I approach this with Reform? I understand that Reform tries to be agnostic of underlying ORM.

**Comment by apotonick** [comment]
It shouldn't create a _new_ `Job` instance for an existing profile! The `:populate_if_empty` is only invoked when the incoming hash contains a `job:` fragment but the profile form does not have a job form.

Can you paste how you create the "update" form as in my example?

```ruby
profile = Profile.find(1)
form = ProfileForm.new(profile)

puts form.jobs.inspect
```

I want to see the object graph. Also, I need to know the params to pass to `validate`. Aaaaand: I wrote more docs, here: http://trailblazerb.org/gems/reform/populators.html

Not sure but you might wanna read this, too: http://trailblazerb.org/gems/reform/populators.html#populating-by-id

**Comment by tokenvolt** [comment]
@apotonick thanks, your links to the docs have clarified the issue

**Comment by apotonick** [comment]
So did you get it working? Can I see some code?

**Comment by tokenvolt** [comment]
@apotonick Yes, I did, thank you! Your gem is really helping a lot. I have pretty complex 3-level nested forms and it works like a charm =)
