### ISSUE TITLE
getting ArgumentError - Unknown validator: 'UniquenessValidator'

### ISSUE THREAD

**Issue by deneuxa** [apotonick/reform#286]
Since I update to Reforme Release 2 I have this error when using uniqueness  validation : 

validates :name, presence: true, uniqueness: true

**Comment by apotonick** [comment]
Please use `validates_uniqueness_of` or `unique: true` then as described here: http://trailblazerb.org/gems/reform/validation.html#uniqueness-validation

The problem is ActiveModel's weirdness when trying to be smart about how to find the `UniquenessValidator` constant.

Please also note that I will drop support for ActiveModel validations in Reform 2.1 (they will still work but the new validations will be so much better that you won't even think about AM-based validations anymore). :wink:

**Comment by svoop** [comment]
@apotonick 

This is most likely related: I'm currently migrating an app from Rails 4.1 to 4.2 and one of the forms uses `copy_validations_from` like so:

    class UserForm < Reform::Form
      properties :email, :first_name, :last_name, :locale
      extend ActiveModel::ModelValidations
      copy_validations_from User
    end

The User model has several validations such as:

    validates :email, :first_name, :last_name, presence: true
    validates :email, uniqueness: { case_sensitive: false }
    validates :locale, inclusion: { in: I18n.available_locales.agnostify }

The app boots in `development`, but it fails to boot in `production` with:

    /(...)/activemodel-4.2.5/lib/active_model/validations/validates.rb:120:in `rescue in block in validates': Unknown validator: 'UniquenessValidator' (ArgumentError)

Only the uniqueness validator shows this behaviour, others such as the presence validator work normally. And if I change the `eager_load` config to `true`, the app boots in `production` as well.

Now, I would be more than happy to reform all forms, but some bits of the app expect validations on the models (OmniAuth, ActiveAdmin). However, eager loading everything in production doesn't feel like a good idea, maybe there's a way to just eager load UniquenessValidation?

For now, I'm dropping `copy_validations_from` and dupe the necessary validations there, not very DRY though.

**Comment by schrockwell** [comment]
The Reform documentation for this feature now lives at: http://trailblazer.to/gems/reform/validation.html#uniqueness-validation

**Comment by apotonick** [comment]
..."feature" :grimacing: 

My advice is not to use `copy_validations_from` (as you already said, @svoop) because in TRB validations sit in forms and not in models, anyway. Then, use the `unique` validator and you should be good to go.

**Comment by artur79** [comment]
> Please also note that I will drop support for ActiveModel validations in Reform 2.1 (they will still work but the new validations will be so much better that you won't even think about AM-based validations anymore). 😉

@apotonick are you talking here about dry-validations ?

**Comment by apotonick** [comment]
Yes!!! :laughing: 

Don't worry, though, we will keep supporting AMV.

**Comment by artur79** [comment]
Are those dangers about about changing model state for _unique_ and _confirm_ validations still present in new Rail's versions like 5.1 ?

**Comment by apotonick** [comment]
No idea, would be interesting to find out, though!

**Comment by konung** [comment]
Yep, it will still be an issue. it has nothing to do with RailsOr TRB or dry-validations . It’s also an issue in any other language or framework
The only way to avoid it from app itself is to issue a table lock while inserting a new record and validation . It’s extremely slow and I performant. If you want to insure unique key, always setup a unique index on the DB ( and duplicate in your validations , as well as catch NotInique errors and handle them nicely)

Hope that helps
