### ISSUE TITLE
Single property populator is throwing an error

### ISSUE THREAD

**Issue by tmullen** [apotonick/reform#287]
Hey Nick, I'm having trouble getting the populator to work for a single property in my form. An `undefined method 'from_hash' for #<Loan:0x007fcec41b4280>` is thrown when trying to set this for some reason. It looks like the object is found and set, but is not able to be deserialized? Not quite sure I understand what's happening under the covers.

Here's the code:
```ruby
class CartItem::CreateForm < Reform::Form
  property :amount, validates: { numericality: { greater_than: 0 } }
  property :loan,
    populator: ->(params, *) {
      loan ? loan : self.loan = Loan.find_by(id: params[:id])
    }

  validate :minimum_investment_amount?

  def minimum_investment_amount?
    return unless amount < loan.investment_min
    errors.add :amount, "must be greater than minimum"
  end
end
```
And accompanying spec:
```ruby
describe CartItem::CreateForm do
  let(:item) { CartItem.new }

  subject { described_class.new(item) }

  context "when amount is less than investment minimum" do
    let(:loan) { create(:loan, investment_min: 1000) }
    let(:attributes) { {loan: {id: loan.id}, amount: 100} }

    it { expect(subject.validate(attributes)).to be_falsey }
  end
end
```
Any help would be much appreciated.

trailblazer (0.3.3)
reform (2.0.3)

**Comment by apotonick** [comment]
The form doesn't understand that this is a nested object and hence doesn't wrap the added `Loan` into a nested form. Try the following

```ruby
property :loan,
    populator: ->(params, *) {
      loan ? loan : self.loan = Loan.find_by(id: params[:id])
    }, do end
```

Anyway, this is weird as the deserializer for this non-nested scalar property shouldn't be called. Can you report if that works for you? I will then further investigate. :wink:

**Comment by tmullen** [comment]
When I do that (assuming the comma above was a typo), the referenced 'loan' object inside `minimum_investment_amount?` becomes some type of wrapper object (ActiveModel::Errors?) instead of the loan itself.
```
<#<Class:0x007fa7a50f99d0>:0x007fa7a47882e8 @fields={}, @model=#<Loan id: 1, ... >>, @_changes={}, @errors=#<Reform::Contract::Errors:0x007fa7a479bd20 @base=#<#<Class:0x007fa7a50f99d0>:0x007fa7a47882e8 ...>, @messages={}>>
```

**Comment by tmullen** [comment]
And on a separate but related note, is this the preferred way to set up the form object for this case? The `CartItem` model is set as `<CartItem :id, :loan_id, :amount, ...>`, so it feels a bit odd to have a nested param structure with `{loan: {id: 123}, amount: 100}`. The loan is only meant to be referenced and not changed in any way.  Mainly, I just want to make sure I'm headed in the right direction here.  

Thanks for the quick responses!

**Comment by fran-worley** [comment]
@tmullen just a quick bump to see how you got on. Do you need any more help here or have you got things sorted?

**Comment by tmullen** [comment]
All is sorted. I ended up going a different direction using `property :loan_id` instead.

Will go ahead and close this. Thanks for the reminder. 👍
