### ISSUE TITLE
Validation does not get true

### ISSUE THREAD

**Issue by Calamari** [apotonick/reform#288]
Given the following code, I would expect the first validation call to return `false` and the second one to return `true`. 

```ruby
require 'reform'
require 'ostruct'

require "reform/form/active_model/validations"
Reform::Form.class_eval do
  include Reform::Form::ActiveModel::Validations
end

class MyForm < Reform::Form
  property :body, validates: {presence: true}
end

myModel = OpenStruct.new

form = MyForm.new myModel

p "Empty Validate: #{form.validate({})}"

p form.errors

p "body: #{form.body}"
p form.errors

p ""
p "filled Validate: #{form.validate({ body: 'lala', foo: false})}"

p "body: #{form.body}"
p form.errors
```

So the actual output is:

```bash
$ ruby test.rb
"Empty Validate: false"
#<Reform::Contract::Errors:0x007fd5ea215620 @base=#<MyForm:0x007fd5ea21f0f8 @fields={"body"=>nil}, @model=#<OpenStruct>, @mapper=#<#<Class:0x007fd5ea21f008>:0x007fd5ea21ed88 @model=#<OpenStruct>>, @_changes={}, @errors=#<Reform::Contract::Errors:0x007fd5ea215620 ...>>, @messages={:body=>["can't be blank"]}>
"body: "
#<Reform::Contract::Errors:0x007fd5ea215620 @base=#<MyForm:0x007fd5ea21f0f8 @fields={"body"=>nil}, @model=#<OpenStruct>, @mapper=#<#<Class:0x007fd5ea21f008>:0x007fd5ea21ed88 @model=#<OpenStruct>>, @_changes={}, @errors=#<Reform::Contract::Errors:0x007fd5ea215620 ...>>, @messages={:body=>["can't be blank"]}>
""
"filled Validate: false"
"body: lala"
#<Reform::Contract::Errors:0x007fd5ea1e6ca8 @base=#<MyForm:0x007fd5ea21f0f8 @fields={"body"=>"lala"}, @model=#<OpenStruct>, @mapper=#<#<Class:0x007fd5ea21f008>:0x007fd5ea21ed88 @model=#<OpenStruct>>, @_changes={"body"=>true}, @errors=#<Reform::Contract::Errors:0x007fd5ea1e6ca8 ...>>, @messages={:body=>["can't be blank"]}>
```

That's a bug right? Or should I use the form object differently?

P.S.: That also happens with real ActiveRecord objects, I put in an OStruct instance, to make the test file simpler and to just be callable like that.

**Comment by apotonick** [comment]
Calling `#validate` twice is not supported by Reform, it simply doesn't make sense to validate a form twice. This issue discusses this already: https://github.com/apotonick/reform/issues/282

**Comment by apotonick** [comment]
BTW, we could think about clearing the `errors` in `#validate` but I'm not sure if I really want to encourage people to do so. The form is a throw-away object and shouldn't be reused...?!?!? :wine_glass:

**Comment by Calamari** [comment]
Good to know.

But I don't exactly get the reason why `validate` should not work the second time.. I mean, if it is possilbe to call it twice, then I would also thing it works the same way, and not change it's behavior.
But I guess, I should discuss that in #282 then.
