### ISSUE TITLE
Problem when saving special attributes

### ISSUE THREAD

**Issue by eljojo** [apotonick/reform#290]
Hi Nick and Reform people!

I found this weird edge-case that I'm not fully sure how to explain, so I just wrote a test for it. You can find it here: https://github.com/apotonick/reform/compare/master...eljojo:bug

If I define a model with a read-only attribute (no ``attr_writer``, just ``attr_reader``) reform tries to overwrite it and things go awry.

A minimal version is:

```ruby
Artist = Struct.new(:name)

class Album < Struct.new(:artist)
  def special_artist
    artist
  end
end

class SpecialArtistForm < Reform::Form
  property :special_artist do
    property :name
  end
end

album = Album.new(Artist.new("test"))
test_form = SpecialArtistForm.new(album)
test_form.validate(special_artist: {name: "Queens of The Stone Age"})
test_form.save
```

The raised exception is:

```
NoMethodError: undefined method `special_artist=' for #<SaveTest::Album:0x007faf4a6178c0>
    /Users/jojo/.gem/ruby/2.2.3/gems/disposable-0.1.12/lib/disposable/expose.rb:33:in `block in accessors!'
    /Users/jojo/.gem/ruby/2.2.3/gems/disposable-0.1.12/lib/disposable/twin/sync.rb:49:in `block in sync!'
    /Users/jojo/.gem/ruby/2.2.3/gems/disposable-0.1.12/lib/disposable/twin/representer.rb:34:in `block in each'
    /Users/jojo/.gem/ruby/2.2.3/gems/disposable-0.1.12/lib/disposable/twin/representer.rb:28:in `each'
    /Users/jojo/.gem/ruby/2.2.3/gems/disposable-0.1.12/lib/disposable/twin/sync.rb:37:in `sync!'
    /Users/jojo/.gem/ruby/2.2.3/gems/disposable-0.1.12/lib/disposable/twin/sync.rb:24:in `sync_models'
    /Users/jojo/.gem/ruby/2.2.3/gems/disposable-0.1.12/lib/disposable/twin/save.rb:5:in `save'
    /Users/jojo/code/reform/test/save_test.rb:77:in `block in <class:SaveTest>'
```

Defining a ``special_artist=(_)`` no-op method does the job, but I thought it'd be worth sharing here.

**Comment by apotonick** [comment]
Sure thing, every property is written to the model in `sync`. How would Reform know it's not supposed to do that? You have to define it `writeable: false`.

**Comment by eljojo** [comment]
With the following form:
```ruby
class SpecialArtistForm < Reform::Form
  property :special_artist, writeable: false do
    property :name
  end
end
```

The test still fails. This time with:
```
Expected: "Queens of The Stone Age"
  Actual: "Bad Religion"
```

Why would the ``special_artist`` property be overwritten in the model?

**Comment by apotonick** [comment]
Where does the `"Bad Religion"` come from? Tell me on https://gitter.im/trailblazer/chat

**Comment by fran-worley** [comment]
I'm closing this as it's gone a little stale. For help or queries please use the trailblazer gitter channel. Issues are reserved for bugs and their fixes. Thanks 😺
