### ISSUE TITLE
Problem with contract in modules

### ISSUE THREAD

**Issue by jfreitasdutra** [apotonick/reform#292]
Hi Nick, in Railsblcoks project, in entitities gem (https://github.com/railsblocks/railsblocks-entities), we are reusing a contract in two models, puting this in a module
https://github.com/jfreitasdutra/railsblocks-entities/blob/master/app/models/entities/manager/company/profile/contract.rb
the same for Entities::Organization https://github.com/jfreitasdutra/railsblocks-entities/blob/master/app/models/entities/organization/profile/contract.rb

But when I try to test the Entities::Profile::Contract isolated
https://github.com/jfreitasdutra/railsblocks-entities/blob/master/spec/models/entities/profile/contract_spec.rb
I can validate without ovveride methods :/. I tried test looking your test in reform and trailblazer gems.

**Comment by apotonick** [comment]
You're overriding `::included` in your contract module but you don't call `super` in it. I guess you misunderstood how a form module works.

```ruby
module Contract
  include Reform::Form::Contract

  property ...
end
```

No need to add your own `included` logic.

**Comment by jfreitasdutra** [comment]
Really, I made a mistake with `included` method. Now I just add a include of `Reform::Form::Module` on base because I use a nested modules. In this [PR](https://github.com/railsblocks/railsblocks-entities/pull/5) has a module with private methods to define the populators in lambda of properties, and one test for it.
