### ISSUE TITLE
ActiveModel Translation woes

### ISSUE THREAD

**Issue by doppelreim** [apotonick/reform#293]
Hi there :)

I ran into a problem with translations of attribute names using reform with rails.
I think the problem is somewhat related to the changes introduced in `281ab649cf4898`.

I tried to create a failing test, but was not able to get the test-suite running.
Executing `bundle exec rake test_rails` complains about `config.eager_load is set to nil` and when I set it to `false` it aborts with `no implicit conversion of Array into String (TypeError)`.

Anyway, I created a little rails-app that showcases the error: https://github.com/doppelreim/reformtest
It's a default rails-app with one scaffolded `Album` model with one attribute `name`.
There are translations in `/config/locales/en.yml`.
The `AlbumForm` validates presence of `name`.

When you visit `http://localhost:3000/albums/new`, the translations are not used.
When you submit the form without providing a name, the form is rendered again, with an error message. But now, the translations are used. :open_mouth:
When you restart the rails-server, the translations are ignored again.

I assume, this is because the hack in `/reform/lib/reform/form/active_model/validations.rb:72` is only applied before validation, and not when the form is displayed for the first time.

I was able to "solve" the problem by adding a constructor to the `AlbumForm` that sets the `model_name` of the `validator` (see /reformtest/app/forms/album_form.rb).
If you comment-in the constructor, the problem goes away - as far as I can tell.

I wouldn't be surprised if there's a better/cleaner way to do this. But reading the `active_model/validations.rb` file, I got confused with all the included eigenclass business :blush:

And of course it could very well be, that I messed some other thing up and in reality there is no bug at all :)

**Comment by apotonick** [comment]
It's most definitely a bug, originating from the brain-dead way ActiveModel::Validations computes its translation keys. I don't do class instance voodoo because I'm awesome but because the whole logic in AM (again, it is complete rubbish) relies on a mix of instance and class methods which is extremely hard to satisfy if you're not in an ActiveModel object.

Thanks for your report, I think what you guess is right. I might have a look after the weekend. :beers:

**Comment by mipearson** [comment]
This is biting me now. I'm tempted to override `human_atttribute_name` on our forms to get it to do something consistent.

This is the second time I've been bitten by AM & Reform not playing nice, I'm wondering whether a solution is to reimplement AM::Validations to be sensible.

**Comment by apotonick** [comment]
Yes, we will most probably focus on dry-validations and just leave AM:V and all its crap where it is.

**Comment by jonknapp** [comment]
As a heads up, I added the following to my `Forms` and was able to reference translations at `activemodel.attributes.[namespace/form_class].[attribute]`.

```
def self.human_attribute_name(attribute_key_name, options = {})
  I18n.t("activemodel.attributes.#{self.to_s.underscore}.#{attribute_key_name}", options)
end
```

**Comment by fran-worley** [comment]
@mipearson Reform has now made the switch from ActiveModel::Validations as a default to dry-validations. If you're still struggling with this and @jonknapp suggestion works we could maybe include it in the reform-rails gem which now houses all ActiveModel/ raise code.

**Comment by mipearson** [comment]
Cool!

I think, unfortunately, that we're going to be moving off of ReForm and using something more lightweight internally - this is more to do with our own architecture than any comment on ReForm's quality.

**Comment by apotonick** [comment]
One day I'm gonna compile a list of all the "Hey, we don't use your gems anymore, we've built something better and lighter based off your work" messages haha, it will be hilarious. #opensourcelife

**Comment by apotonick** [comment]
@mipearson Any chance to outline your internal architecture? Just curious about learning other views and perspectives..!

**Comment by mipearson** [comment]
More that we're much more "vanilla Rails" than Reform wants, and we're making an effort (after a couple of bad calls - draper/pundit being a couple of others) to strip back third party Rails extensions as they often conflict with how Rails wants us to do things (this being a good example).

Rails is full of magic. Reform is also magic. When you combine them, weird stuff happens.

**Comment by apotonick** [comment]
Ah ok, I understand! Thanks!
