### ISSUE TITLE
unique_validator does not use Rails i18n translations

### ISSUE THREAD

**Issue by audionerd** [apotonick/reform#294]
I think it just needs a fix to this line:
https://github.com/apotonick/reform/blob/c2db7e661d0d5e8de208c8aadc211e8c8b3a8527/lib/reform/form/validation/unique_validator.rb#L13

... and of course a test! :)
https://github.com/apotonick/reform/blob/c2db7e661d0d5e8de208c8aadc211e8c8b3a8527/test/unique_test.rb

**Comment by apotonick** [comment]
@audionerd As discussed here? https://github.com/apotonick/reform/pull/271

**Comment by audionerd** [comment]
Yep, looks like a dupe of #271.
