### ISSUE TITLE
Model Validations - move or not move

### ISSUE THREAD

**Issue by aaani** [apotonick/reform#316]
I have a question. I read the documentation and it seems like it's discouraged to keep validations in the model, which works great when data is being saved to model only from the forms. But I save data from rake tasks too, and I want to be able to run model validations before saving/updating etc from there. Is there any good way to handle this?
PS I know about copy_validations_from and I can't use it because it brings in all the validation from model. I have a massive model with lots of validation. So I broke down user entry in 2 forms, for form-1 I want to certain validations only and similarly for form-2 I want to run certain other validations.

Thanks!

**Comment by apotonick** [comment]
I absolutely discourage using this feature, and I also do not advise you to use models directly anymore (e.g. from rake tasks) but rather use an operation that encapsulates validates and persistence logic. Check this out: https://github.com/apotonick/trailblazer#validations

The `copy_validations_from` feature is nice to quickly play with forms, but it breaks down as soon as you use custom validations or broken validators from ActiveRecord that write to the model (confirmation, acceptance, and so on). Please don't use it, and let me know if you need help with anything!
