### ISSUE TITLE
Nested form is not updated

### ISSUE THREAD

**Issue by GCorbel** [apotonick/reform#317]
Hi,

I create a form with Reform 2.0.5 like this : 

    class OrderForm < Reform::Form
      property :email 

      collection :line_items, populate_if_empty: LineItem do
        property :color_id
      end
    end

And I have this code : 

    order = Order.find(id)
    @form = OrderForm.new(order)
    @form.validate(params)
    p @form.line_items.count

In this code, params is : 

    {"email"=>"test@test.com",
     "line_items_attributes"=>
      {"0"=>{"color_id"=>2 },
       "1"=>{"color_id"=>2}}}

`order.line_items.count` is five and it's normal, I have five line items in the order I want to update. Before `form.validate`, `form.line_items.count` its five because it takes the line items of the order. After `form.validate`, `form.line_items.count` still five which is not what I expect. I think it should be two.

The email address is updated correctly.

How can I update the number of line items of the form ?

Thanks.

**Comment by GCorbel** [comment]
I have the same with issue with the master branch.

**Comment by Titinux** [comment]
It's maybe a naming problem. Your collection is named line_items and I think you should pass an array named line_items instead of line_items_attributes.

**Comment by apotonick** [comment]
The name `line_items_attributes` is OK since you have Rails support included in your form (which maps the weird Rails name to the attribute name @Titinux refers to).

You are using `:populate_if_empty` which will only be called when your form object doesn't have a nested line items form for the incoming item. You need to use another populator that overwrites your original collection. http://trailblazer.to/gems/reform/populators.html

**Comment by GCorbel** [comment]
@Titinux, I change `line_items_attributes` for `line_items` and I have `NoMethodError: undefined method `has_key?' for #<Array:0x0000000a1a0158>`.

@aptonick, I included `include Reform::Form::ActiveModel`, I removed all prepopulation and I have the same behaviour. I tried to add a populator lambda and it's never triggered.

Any idea?

**Comment by apotonick** [comment]
@GCorbel When you add `populator:` it will be called for every item, always. Maybe you're passing in the wrong key? Are you in a Rails environment?

**Comment by GCorbel** [comment]
@apotonick , you were right. I did a mistake somewhere but it works now. Thanks for your help.
