### ISSUE TITLE
SimpleForm does not found the I18n keys from activerecord.attributes in Reform 2.0

### ISSUE THREAD

**Issue by Sylvain** [apotonick/reform#320]
Hi!

In Reform 1.2, I used SimpleForm and translated the attributes in en.activerecord.attributes.model_name.attribute_name. When using Reform, SimpleForm was able to find the matching translations. In Reform 2.0, SimpleForm does not find the translations anymore.

Do you have any idea on how to let SimpleForm find the translations again?

Many thanks by advance.

Kind regards

Sylvain

**Comment by apotonick** [comment]
The top key has changed to `activemodel` but I can try to fix it for 2.1.

**Comment by Sylvain** [comment]
Thanks for your quick reply @apotonick. The thing is, even if I override the key by defining:
```ruby
  def self.i18n_scope
    :activerecord
  end
```

in the form. The translations are still not found. I don't know I could try to fix it.

**Comment by Sylvain** [comment]
I added a Rails test app for you to reproduce: https://github.com/Sylvain/reform2

Let me know if I can help in any way.

**Comment by apotonick** [comment]
Overriding on the form doesn't help. I don't include the `ActiveModel::Validations` mess into the form anymore, but into a separate validator object:https://github.com/apotonick/reform/blob/36b2e260cc004b69dd23f235fec67f64154f2e3d/lib/reform/form/active_model/validations.rb#L69

 That's where we have to configure that. It's such a mess, I am looking forward to the days where we drop AM:V.

**Comment by fran-worley** [comment]
As of Reform 2.2 all active model / active record related code has moved to the [reform-rails gem](https://github.com/trailblazer/reform-rails).

If you're still experiencing this issue, please can you reopen it in the correct gem. Thanks 😺

**Comment by lucaspiller** [comment]
@Sylvain Here I how I got i18n working with Reform + SimpleForm.

I have a form setup like this (Slim syntax):

```ruby
= simple_form_for(@form, as: :new_configuration_form) do |f|
  = f.input :configuration_type
```

Then in my locale file I have this:

```yml
en:
  simple_form:
    labels:
      new_configuration_form:
        configuration_type: 'Type'
```

If you add this to an initialiser, it will print out what i18n keys SimpleForm is looking for. Note that it doesn't search the ActiveRecord scopes:

```ruby
module SimpleForm
  module Inputs
    class Base
      def translate_from_namespace(namespace, default = '')
        model_names = lookup_model_names.dup
        lookups     = []

        while !model_names.empty?
          joined_model_names = model_names.join(".")
          model_names.shift

          lookups << :"#{joined_model_names}.#{lookup_action}.#{reflection_or_attribute_name}"
          lookups << :"#{joined_model_names}.#{reflection_or_attribute_name}"
        end
        lookups << :"defaults.#{lookup_action}.#{reflection_or_attribute_name}"
        lookups << :"defaults.#{reflection_or_attribute_name}"
        lookups << default

        puts lookups.inspect

        I18n.t(lookups.shift, scope: :"#{i18n_scope}.#{namespace}", default: lookups).presence
      end
    end
  end
end
```

**Comment by zavan** [comment]
@lucaspiller 

"Note that it doesn't search the ActiveRecord scopes"

It doesn't look up by itself, but it delegates to `model.class.human_attribute_name` if it doesn't find the translation in the simple_form scope and the model class (in our case the form class) responds to `human_attribute_name` (which does look up in the activerecord scope):

https://github.com/plataformatec/simple_form/blob/c3a307cb9501208e053f771738e34a3d93d33858/lib/simple_form/components/labels.rb#L71-L72

Should Reform delegate `human_attribute_name` to the model class, in the `Reform::Form::ActiveModel` module, @apotonick?
