### ISSUE TITLE
Error messages are duplicate

### ISSUE THREAD

**Issue by acaron** [apotonick/reform#323]
In the latest version on master branch, error messages are duplicated if you do this:
`property :first_name, validates: { presence: true }`
I receive: `"last_name"=>["can't be blank", "can't be blank"]`

But it is ok if you do this:
```
property :first_name
validates :first_name, presence: true
```
I receive: `"last_name"=>["can't be blank"]`

**Comment by gcoderre** [comment]
Same here, using reform 2.1.0 and lotus-validations 0.4.0. I've created a failing test case to confirm that:
https://github.com/gcoderre/reform-duplicate-errors

It seems to be fixed in 2.2.0, though, but I'm not sure what fixed it.

**Comment by fran-worley** [comment]
If this is fixed can we close? @acaron any luck?

**Comment by fran-worley** [comment]
As of Reform 2.2 all active model / active record related code has moved to the reform-rails gem.

If you're still experiencing this issue, please can you reopen it in the correct gem. Thanks 😺
