### ISSUE TITLE
Reusing Modules across Form objects that both use and don't use Composition

### ISSUE THREAD

**Issue by j-clark** [apotonick/reform#327]
So, I commonly find myself needing to update models in one way for an admin user and another way for a non-admin user

For example, our user might be signing up as a new artist and be asked various questions that will prompt further questions based on those answers. We might have forms that look like such

```ruby
class ArtistForm < Reform::Form
  property :name
  property :goes_on_tour
  property :sell_swag
end
```

If the user says "Yes" to `goes_on_tour`, we're going to ask more questions about that on a subsequent page. Perhaps with a form like:

```ruby
class TouringProfileForm < Reform::Form
  property :favorite_month_to_tour
  collection :touring_partners do
    property :name
  end
end
```

Cool, right? Then we've got an admin user that has a different workflow. She wants to go in and edit the touring profile as a whole. So we end up with a form that looks like this:

```ruby
class Admin::TouringProfileForm < Reform::Form
  include Composition

  property :goes_on_tour, on: :artist
  property :favorite_month_to_tour, on: :touring_profile
  # ... more_stuff, on: :touring_profile
end
```

That's a contrived example, but the duplication is obvious. Now add in complex validations and more and you really start wanting to just straight up reuse the existing forms. There's two options that I can currently see to achieve this: extract the contents of the `TouringProfileForm` into a `Module` and include it in the two places. But this doesn't work since one uses `Composition` and the other doesn't! The other option, which admittedly _does_ work:

```ruby
class Admin::TouringProfileForm < Reform::Form
  include Composition

  property :goes_on_tour, on: :artist
  property :touring_profile, form: TouringProfileForm
end
```

However, that doesn't have the same structure as the duplicated example. All the touring profile stuff is nested. In the real life problem I'm trying to solve, I have this form backing an API and I don't want to enforce a specific structure on my consumers that doesn't make sense.

It'd be great if I could use `Modules` interoperably across `Composition` and non-`Composition` `Form`s. Or am I missing another approach?

**Comment by apotonick** [comment]
The `Form::Module` should work for both approaches as long as you include it *after* including `Composition`, because it really just replays the declarations (use reform/master until 2.1 gets released, though!).

```ruby
module SharedProperties
  include Reform::Form::Module
  property :goes_on_tour, on: :artist # the :on is ignored in non-Composition.
end
```

Then, include that.

```ruby
class TouringProfile::Form < Reform::Form
  include Composition
  include SharedProperties
end
```

Is that what you need?

**Comment by j-clark** [comment]
Yes, that effectively worked. I'm not currently up-to-date with the latest reform and don't have the capacity to upgrade, so here's what worked for those unable to track master at the moment:

```ruby
module SharedProperties
  def self.included(base)
    base.class_eval do
      property :goes_on_tour, on: :artist
    end
  end
end
```

And so on. The rest of the implementation matches yours. Thanks!

**Comment by apotonick** [comment]
In Reform 2.0, once the module was included properties were "natively" created and then inherited using a rather complex inheritance mechanism, in Reform 2.1, those `property` calls are simply "remembered" and re-evaluated when inheriting/including.

You should update to 2.1 once it's released - the public API hasn't changed, only that we deprecate a few things to make it more awesome.

Thanks for the snippet to help others. :heart:
