### ISSUE TITLE
to_h for contract

### ISSUE THREAD

**Issue by nikitasherman** [apotonick/reform#329]
Hi, I would like to ask for a method (to_h)
which will allow me to get populated hash representation of the contract
without the "fields" key in each level in case of nested forms, actually even for the
first level it's all nested within @fields.

**Comment by apotonick** [comment]
`Form#to_nested_hash` :wink:

**Comment by fran-worley** [comment]
@nikitasherman if you're still stuck fee free to reopen but I'm going to close this as you've got an answer :)
