### ISSUE TITLE
Date validation

### ISSUE THREAD

**Issue by mateuszgorniak** [apotonick/reform#331]
Hi!
I wanted to use https://github.com/codegram/date_validator to validate date but it doesn't work for me - validation returns `true` even for invalid values. Is there an option to make it work with `Reform`? :-)

**Comment by apotonick** [comment]
Best to ask the author of date_validator. I had a look, they override `#validate`, which is not cool.

**Comment by apotonick** [comment]
Here, that must be the problem: https://github.com/codegram/date_validator/blob/master/lib/active_model/validations/date_validator.rb#L41

**Comment by apotonick** [comment]
Oh, sorry, that wasn't right. It must be something else. You should try and figure out if the `Validator` instance in date_validator is called or not. If you set up a super simple test app with a form, and maybe a test invoking the form with a date, I can help! :beers:

**Comment by mateuszgorniak** [comment]
Thx, I'll do this! :-)

**Comment by mateuszgorniak** [comment]
Hi, here's my example app:
https://github.com/mateuszgorniak/ReformDateValidatorTestApp

I started debugging and the first suspected problem I see there is that value is not after type cast here:
https://github.com/codegram/date_validator/blob/master/lib/active_model/validations/date_validator.rb#L43

Is there an option to do this? even adding `type: DateTime` doesn't work here :(

**Comment by apotonick** [comment]
Have you included `Coercion` into your form to force type-casting?

**Comment by mateuszgorniak** [comment]
Yes, I've already pushed it. The same result :(

**Comment by mateuszgorniak** [comment]
Using `validate_each(record, attribute, ActiveRecord::Type::DateTime.new.send(:cast_value, value))` instead of https://github.com/codegram/date_validator/blob/master/lib/active_model/validations/date_validator.rb#L44 is working. But I'm sure it shouldn't work this way and we should send value after type-casting in this case.

**Comment by fran-worley** [comment]
Not that it helps if you are set on ActiveRecord validations, but date validation using Dry Validation is really easy provided you are coercing your values.

Because its comparison validators call `>` or `<` under the hood (see here https://github.com/dryrb/dry-logic/blob/master/lib/dry/logic/predicates.rb#L83-L97) you can use its built-in predicates/methods to validate dates.

A simple example, but to validate that your attribute date is greater than today you can call:
```ruby
key(:attribute){ |attribute| attribute.date? & attribute.gt?(Date.today) }
```

**Comment by fran-worley** [comment]
@mateuszgorniak I'm going to close this as active model code and related issues have been moved to the reform-rails gem.

Feel free to reopen and we can revisit but I really would urge you to consider looking at dry-validations :)
