### ISSUE TITLE
[Doc] Fix null matching

### ISSUE THREAD

**Issue by musaffa** [apotonick/reform#338]
There's a subtle bug in [Populator: Match by ID](http://trailblazer.to/gems/reform/populator.html#populator-match-by-id) documentation:
```ruby
collection :songs,
  populator: ->(fragment:, **) {
    # find out if incoming song is already added.
    item = songs.find { |song| song.id.to_s == fragment["id"].to_s }

    item ? item : songs.append(Song.new)
  }
```

If both of song.id and fragment["id"] are null then calling `to_s` on them will return empty strings `""` which will match with each other. I ran into this problem while trying to delete an object in a multi select scenario. Fix is simple: `song.id == fragment["id"].to_i`.

This same problematic code can also be found in multiple places in the documentation. Hope they will be fixed too.

**Comment by apotonick** [comment]
But what if `song.id` doesn't return an `Integer`?

**Comment by musaffa** [comment]
Whether to use `to_i` or not will depend on the implementation. But testing equality with `to_s` on the both sides can be a source of bug if we cannot make sure that the both sides are not null.

**Comment by apotonick** [comment]
Maybe you're right, most ORMs will return an integer for `#id`, right?
