### ISSUE TITLE
cannot load such file -- dry-validation

### ISSUE THREAD

**Issue by n-rodriguez** [apotonick/reform#339]
From documentation I should put this in an initializer: 

```
require "reform/form/dry"
Reform::Form.class_eval do
  feature Reform::Form::Dry
end
```

This prevents Rails to start.

If I put the block directly in the form, I get this : ```cannot load such file -- dry-validation```.

This line seems to break validation loading : https://github.com/apotonick/reform/blob/master/lib/reform/form/dry.rb#L1.

**Comment by n-rodriguez** [comment]
Actually you need to install https://github.com/dryrb/dry-validation :

```gem 'dry-validation'```

**Comment by davidalejandroaguilar** [comment]
This should be in the documentation!

**Comment by sachins1812** [comment]
I ran into the similar problem when i try to bundle update my project

/home/system/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- dry/types/compat/form_types (LoadError)
