### ISSUE TITLE
How to properly tackle with has_one polymorphic associations?

### ISSUE THREAD

**Issue by sergio1990** [apotonick/reform#344]
Hi, guys! I have a question: how to properly tackle with has_one associations? I’ll show the example with which I stuck.

For example, I have models Post and Image:

```ruby
class Post < ActiveRecord::Base
	has_one :cover, class_name: 'Image', as: :imagable
end

class Image < ActiveRecord::Base
	belongs_to :imagable, polymorphic: true
end
```

And I have form object to create/update some post:

```ruby
class PostForm < Reform::Form
	property :cover, skip_if: :skip_cover_process!, populator: :populate_cover! do
		# Image is processed by another API endpoint and there only id is passed
		property :id
		property :_destroy, virtual: true
	end

	def skip_cover_process!(fragment:, **)
		if fragment['_destroy'] == 'true'
			# ???
		end
	end
	
	def populate_cover!(fragment:, model:, **)
                #…
	end
end
```

So how to properly break the association? The only one solution which I found and it works for me is:

```ruby
def skip_cover_process!(fragment:, **)
    if fragment['_destroy'] == 'true'
        image_id = self.cover.id
        image = ::Image.find(image_id)
        image.update_attributes imagable_id: nil, imagable_type: nil
        return true
    end
end
```

I use reform 2.1.0.

Thanks.

**Comment by apotonick** [comment]
If you want all those features (create/retrieve and delete) you currently have to write your own populator, you don't need `:skip_if`, you can do that in the populator, too, using `skip!`. http://trailblazer.to/gems/reform/populator.html#delete

**Comment by sergio1990** [comment]
@apotonick thanks for the response!
But what I must do in the populator?
Regarding to the example which you propose by link, in the case of _has\_many_ association I do that:

```ruby
```

**Comment by sergio1990** [comment]
@apotonick thanks for the response!
But what I must do in the populator?
Regarding to the example which you propose by link, in the case of has_many association I do that:

**Comment by sergio1990** [comment]
@apotonick thanks for the response!
But what I must do in the populator?
Regarding to the example which you propose by link, in the case of has_many association I do that:
```ruby
songs.delete(item)
```
And by this code I break association.
But in the case of has_one association what I must do?

**Comment by sergio1990** [comment]
I mean that just call `skip!` does not break association, is it?

**Comment by fran-worley** [comment]
If you have queries on how to use Reform, please read the docs on the [trailblazer site](http://trailblazer.to/gems/reform/), read the (book)[https://leanpub.com/trailblazer], or post your question on the (Trailblazer gitter room)[https://gitter.im/trailblazer/chat]. 

Github issues are now restricted to bug reports and fixes.

We look forward to seeing you on Gitter!
