### ISSUE TITLE
Lookup table with collection_select and belongs_to

### ISSUE THREAD

**Issue by danieldraper** [apotonick/reform#348]
I am trying to get a lookup table `Organisation` to display as a drop down on a form, however having some difficulty, what am I missing?

I have tried a few different things around `property :organisation_id` and haven't managed to get anything working yet.

Using Reform via Trailblazer.

```ruby
class Account < ActiveRecord::Base
  belongs_to :organisation
end
```

```ruby
class Organisation < ActiveRecord::Base
  has_many :accounts
end
```

```ruby
module Registration::Contract
  class Create < Reform::Form
    model Account

    property :name
    property :subdomain
    property :organisation_id
  end
end
```

```ruby
= simple_form_for @form do |form|
  = form.input :name
  = form.input :organisation_id, as: :select
  = form.input :subdomain

  = form.button :submit
```

Update - I have been able to get this working by setting a variable in the controller

```ruby
@organisations = Organisation.all
```

and then in the contract

```ruby
property :organisation_id
```

and the view

```ruby
= form.input :organisation_id, collection: @organisations
```

Doesn't feel right and still open to feedback on this, cheers.

**Comment by apotonick** [comment]
That is a simple_form issue, Reform doesn't have any knowledge about how collections of models should be *rendered*.

I am envisioning a mix of Reform, Cells and Formular to solve this nicely, since the form/controller shouldn't know  `Organisation` model details.

**Comment by fran-worley** [comment]
@danieldraper as Nick said, this is not an issue with Reform itself. SimpleForm requires a seemingly never ending number of methods to be defined for all of its inferring helpers to work. 

This is lead us to build our own inference & magic free form builder which doesn't depend on the rails view helpers at all. Introducing [Formular](https://github.com/trailblazer/formular)! 

We won't be making any more changes to support SimpleForm helpers, so I'm going to close this.
