### ISSUE TITLE
Control the order of errors using custom validation

### ISSUE THREAD

**Issue by jesseiqmi** [apotonick/reform#351]
I just finished running the gauntlet on getting Reform implemented and now just fine tuning my first form that uses a collection and dealing with errors being displayed back to the user. I'm using reform and reform-rails 2.1 with Rails 4.2.x.

When I drop in a custom validator for the collection and using `errors.add(:something, 'at least one is required)` it gets added first, then as the rest of the reform validations kick in they get added afterwards.

Example:
```ruby
property :title
property :date

validates :title, presence: true
validates :date, presence: true
validate :validate_at_least_one_foo

collection :foos do
  property :thing1
  property :thing2
end

def validate_at_least_one_foo
  errors.add(:foos, 'at least one is required') if foos.size == 0
end
```

Errors as displayed to user if all are triggered:

* Foos - at least one is required
* Thing 1 - is required
* Thing 2 - is required

Any thoughts on how we can control the display order of errors? Ideally, as this deals with a collection of 'foos' at the bottom of the UI page, its order in the error messages as displayed to the user should appear last, not first so that they can address issues from the top of the page first and work down.

Cheers and thanks!

**Comment by fran-worley** [comment]
@jesseiqmi all ActiveModel related code has been moved to the trailblazer/reform-rails gem. 

Reform's errors API is a simple hash it too should respect the order in which the errors are added.
https://github.com/apotonick/reform/blob/master/lib/reform/contract/errors.rb#L26-L29

Looking at your Form, your validation Foos happens first, hense it appearing first. Have you tried reordering them? You could always use validation groups with the `:after` option to force a running order.

**Comment by fran-worley** [comment]
@jesseiqmi I'm closing this as it's not actually an issue with Reform. Catch us on the Trailblazer Gitter channel if you've got any more queries. 😺
