### ISSUE TITLE
Not compatible with dry-validation 0.7

### ISSUE THREAD

**Issue by fnordfish** [apotonick/reform#352]
reform breaks with the dry-validation 0.7 due to a lot of api changes.
I've started to play around a bit, but got stuck with reform's "inherit same group" feature:
https://github.com/apotonick/reform/compare/master...fnordfish:dry-v_0-7?expand=1

**Comment by apotonick** [comment]
Thanks, we will fix this via #347.

**Comment by fnordfish** [comment]
Cool. Haven't seen that ticket. Sorry for the noise.

**Comment by apotonick** [comment]
You're good, man, I prefer 2 tickets than no ticket at all but angry users who're waiting that I magically find out what's broken. :grimacing:
