### ISSUE TITLE
Strange behavior with has_secure_password

### ISSUE THREAD

**Issue by pn-y** [apotonick/reform#354]
Hi there, i'm trying to use form for creating users, but catch a some strange behavior of saving form of model with has_secure_password.

```ruby
class User < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true
end
```
```ruby
class UserForm < Reform::Form
  property :email, type: String
  property :password, type: String
  property :password_confirmation, type: String
  property :password_digest, type: String
end
```
When i'm trying to create user though form.save i'm getting validation error
```ruby
2.3.0 :013 > form = UserForm.new(User.new)
 => #<UserForm:0x007fb60c0b7a10 @fields={"email"=>nil, "password"=>nil, "password_confirmation"=>nil, "password_digest"=>nil}, @model=#<User id: nil, email: nil, password_digest: nil>, @mapper=#<#<Class:0x007fb60c2e7a88>:0x007fb60c0b6048 @model=#<User id: nil, email: nil, password_digest: nil>>, @_changes={}, @errors=#<Reform::Form::ActiveModel::Errors:0x007fb60c0acb10 @base=#<UserForm:0x007fb60c0b7a10 ...>, @messages={}>>
2.3.0 :014 > form.email = "email@example.com"
 => "email@example.com"
2.3.0 :015 > form.password = 'pwd'
 => "pwd"
2.3.0 :016 > form.password_confirmation = 'pwd'
 => "pwd"
2.3.0 :017 > form.save
   (0.1ms)  begin transaction
   (0.0ms)  rollback transaction
 => false
2.3.0 :018 > form.model.errors
 => #<ActiveModel::Errors:0x007fb60c86aaa0 @base=#<User id: nil, email: "email@example.com", password_digest: nil>, @messages={:password=>["can't be blank"]}>
```
And if i do a dirty hack it works
```ruby
2.3.0 :001 > form = UserForm.new(User.new)
 => #<UserForm:0x007f80d5a49590 @fields={"email"=>nil, "password"=>nil, "password_confirmation"=>nil, "password_digest"=>nil}, @model=#<User id: nil, email: nil, password_digest: nil>, @mapper=#<#<Class:0x007f80d5a48ac8>:0x007f80d5a43348 @model=#<User id: nil, email: nil, password_digest: nil>>, @_changes={}, @errors=#<Reform::Form::ActiveModel::Errors:0x007f80d5a42010 @base=#<UserForm:0x007f80d5a49590 ...>, @messages={}>>
2.3.0 :002 > form.email = "email@example.com"
 => "email@example.com"
2.3.0 :003 > form.password = 'pwd'
 => "pwd"
2.3.0 :004 > form.password_confirmation = 'pwd'
 => "pwd"
2.3.0 :005 > form.save
   (0.1ms)  begin transaction
   (0.0ms)  rollback transaction
 => false
2.3.0 :006 > form.model.password = form.model.password
 => "pwd"
2.3.0 :007 > form.model.save
   (0.1ms)  begin transaction
  SQL (0.4ms)  INSERT INTO "users" ("email", "password_digest") VALUES (?, ?)  [["email", "email@example.com"], ["password_digest", "$2a$10$xKgvATrvdJ6FWQ5gVGhituW6oKagLU5cywJeNQgdFjp3nZpieqy22"]]
   (2.5ms)  commit transaction
 => true
```
Btw in this case all ok.
```ruby
2.3.0 :011 > form = UserForm.new(User.new(email: 'email@example.com', password: 'pwd', password_confirmation: 'pwd'))
 => #<UserForm:0x007fb60cafa950 @fields={"email"=>"email@example.com", "password"=>"pwd", "password_confirmation"=>"pwd", "password_digest"=>"$2a$10$A36dMhJlho22aPNjEnvNwum7iTfuT5qaY0RQ5wjtmAw.U4l0vmvUC"}, @model=#<User id: nil, email: "email@example.com", password_digest: "$2a$10$A36dMhJlho22aPNjEnvNwum7iTfuT5qaY0RQ5wjtmAw...">, @mapper=#<#<Class:0x007fb60c2e7a88>:0x007fb60cafa3b0 @model=#<User id: nil, email: "email@example.com", password_digest: "$2a$10$A36dMhJlho22aPNjEnvNwum7iTfuT5qaY0RQ5wjtmAw...">>, @_changes={}, @errors=#<Reform::Form::ActiveModel::Errors:0x007fb60caf9870 @base=#<UserForm:0x007fb60cafa950 ...>, @messages={}>>
2.3.0 :012 > form.save
   (0.1ms)  begin transaction
  SQL (0.3ms)  INSERT INTO "users" ("email", "password_digest") VALUES (?, ?)  [["email", "email@example.com"], ["password_digest", "$2a$10$A36dMhJlho22aPNjEnvNwum7iTfuT5qaY0RQ5wjtmAw.U4l0vmvUC"]]
   (2.2ms)  commit transaction
 => true
```

What i'm doing wrong?

**Comment by fran-worley** [comment]
Try removing the `password_digest` property from your Reform object. You shouldn't need to interact with that field yourself as has_secure_password does it all for you. 

It is also worth noting that `has_secure_password` includes some validations as default. Depending on how you apply your validations you may wish to turn them off in your model like so:

```ruby
  #turn off validations for has_secure_password as we manually apply them
  has_secure_password validations: false
```

**Comment by pn-y** [comment]
But when you turn off validations you need to specify attr_accessor for :password_confirmation due has_secure_password doesn't provide it without validations. And of course it works.
Anyway it looks too hacky.

**Comment by fran-worley** [comment]
Well it depends on your opinion of where validations belong... 

If you are leaving all of your validations in the model then you can probably get away with leaving has_secure_password to apply its default validations.

I just wanted to make you aware of the 'magic' included in the method for the future as that tripped me up.

You say hacky I say explicit. Why should your model know anything about the `:password_confirmation` attribute? In respect of passwords, all your user model should be responsible for is taking the valid password and encrypting it.

Moving password validations to the Reform object would look something like this:
```ruby
#form  object
class UserPasswordForm < Reform::Form
    property :password, read: false
    property :password_confirmation, virtual: true 

    validate :passwork_ok? do
      errors.add(:password, "Password mismatch") if password != password_confirmation
    end
end

#user model
class User < ActiveRecord::Base
  has_secure_password validations: false
  attr_accessible :password #if you are using protected attributes
end
```
It is much clearer here what is going on, and the only attribute actually being sent to the model is `:password`.

**Comment by apotonick** [comment]
The whole point about Reform is freeing the model from UI elements and validations. `password_confirmation` is a graphical element in your form and has *nothing* to do with your persistence layer, as @fran-worley pointed out very correctly. In no way should that be implemented in the model.

The validation, too, is completely workflow-specific and has nothing to do with the persistence layer. Only because Rails hides this all nicely from you doesn't mean it's correct! :grimacing: 

We like separation of persistence, domain logic, validations and UI. To me, it doesn't look and feel hacky at all. What makes you think so, @pn-y ?

**Comment by pn-y** [comment]
I thought about it some more time, and i ageyy with @fran-worley. 
Thanks for help!

**Comment by apotonick** [comment]
...and if you need any more help, just let us know, @pn-y! :beers:
