### ISSUE TITLE
Can reform be used with refile?

### ISSUE THREAD

**Issue by aaroncass** [apotonick/reform#358]
According to the refile readme, that gem works with any ruby class:
````
class User
  extend Refile::Attachment

  attr_accessor :profile_image_id

  attachment :profile_image
end
````

I am trying to use it with reform as follows:
```
class User < ActiveRecord::Base
  attachment :profile_image
end
class User::Form < Reform::Form
  property :profile_image
end

form = User::Form.new(User.new)
form.validate(profile_image: some_opened_file) { form.save }
puts form.profile_image
>> nil
puts form.model.profile_image
>> nil
```

The above code does not work - profile_image is always nil. Can anyone point me in the right direction please?

**Comment by apotonick** [comment]
Does it work with `validate("profile_image" => file)`.

**Comment by aaroncass** [comment]
I feel so silly ... it was the block syntax for form.validate(). When I switched to "if form.validate ..." everything works as expected. Thanks for your help and for all your awesome work! (Big fan of trailblazer).

**Comment by apotonick** [comment]
Thanks! :heart:
