### ISSUE TITLE
Reform not syncing properly in #validate due to wrong return value in populator

### ISSUE THREAD

**Issue by av-eric** [apotonick/reform#359]
Hi,
I was doing something like this in my populator:

```ruby
def team_permissions_populator( fragment:, ** )
    permission = team_permissions.find { |permission| permission.id.to_s == fragment[ "id" ] }
    if ! permission
      permission = TeamPermissionForm( TeamPermission.new )
      team_permissions.append( permission )
    end
    permission
  end
```

and validations would fail saying some values were not present. After some debugging I found that reform seemed to be wrapping my form into another form copying the values in the fragment into the inner form:

```
#<TeamPermissionForm:0x007f8481a075f0 @fields={"element_type"=>nil, "read"=>nil, "organization"=>nil, "create"=>nil, "write"=>nil, "remove"=>nil, "index"=>nil, "permission_constraints"=>[]}, @model=#<TeamPermissionForm:0x007f8481a0a638 @f\
ields={"element_type"=>"setup", "read"=>"true",...
```

after changing my code to this:

```ruby
def team_permissions_populator( fragment:, ** )
    permission_form = team_permissions.find { |permission| permission.id.to_s == fragment[ "id" ] }
    if ! permission_form
      permission_form = team_permissions.append( TeamPermission.new  )
    end
    permission_form
  end
```

everything worked just fine(my bad, I know... but being new to Rails this doesn't feel like the way collections should behave...). Point being: documentation should say that you have to return exactly the form returned by the collection... perhaps?

Cheers!
Eric

**Comment by apotonick** [comment]
It's because the populator has to return the appended *form* instance, which is clearly documented here: http://trailblazer.to/gems/reform/populator.html#populator-return-value
