### ISSUE TITLE
custom sync being ignored in nested forms

### ISSUE THREAD

**Issue by aaroncass** [apotonick/reform#364]
I am trying to override sync, which works fine in a standalne form, but not if the form is nested e.g.

```
class Song < Reform::Form
  def sync(*args)
    super
    model.custom_code!
  end
end

class Artist < Reform::Form
  property :name
  collection :songs, form: SongForm
end
```

If I call sync on SongForm, everything works as expected. However, if I call sync on ArtistForm, the custom code does not run.

Can someone please point me in the right direction for how to do this correctly?

**Comment by apotonick** [comment]
It has to be `sync!`.

**Comment by aaroncass** [comment]
d'oh! Thanks
