### ISSUE TITLE
Reform forms generator

### ISSUE THREAD

**Issue by quolpr** [apotonick/reform#365]
Can we realise forms generator for rails? Something like:
```
rails g reform:form v1/user_form user_name password
```
That will produce:
```ruby
class V1::UserForm < Reform::Form
  properties :user_name, :password
end
```

**Comment by apotonick** [comment]
Go for it, in https://github.com/trailblazer/reform-rails :+1: !!

**Comment by quolpr** [comment]
Good, will work on it at weekend :)

**Comment by apotonick** [comment]
You can look up how to write and test generators in the `cells-rails` gem!

**Comment by quolpr** [comment]
Ok, thank you!
