### ISSUE TITLE
Wrong module in documentation?

### ISSUE THREAD

**Issue by apacala** [apotonick/reform#366]
Hi, first of all - thanks for the amazing work on Trailblazer ecosystem! :heart:

So here's my issue: I'm trying to use Reform with dry-validation by following the examples from http://trailblazer.to/gems/reform/validation.html. The problem is the following line:

```ruby
feature Reform::Form::Dry
```

which throws:

```
NameError: undefined local variable or method `validation_group_class' for #<Class:0x007f87748d5128>`
```

Looking at [lib/reform/form/dry.rb](https://github.com/apotonick/reform/blob/master/lib/reform/form/dry.rb#L19), I've noticed that it's actually the `Reform::Form::Dry::Validations` module that extends `Reform::Validation` with alll the required functionality.

So after replacting the included module, everything seems to work fine:

```diff
- feature Reform::Form::Dry
+ feature Reform::Form::Dry::Validations
```

Is this intended or just a typo in the docs?

Using:

```
reform 2.1.0
dry-validation 0.7.4
trailblazer 1.1.1
```

Thanks! :heart_decoration:

**Comment by apotonick** [comment]
You need to use the `2-2` branch, but I realize now that I have to release a stable version since you're about the 20th to ask this! :laughing: :joy:
