### ISSUE TITLE
Validating twice in a row does not clear errors

### ISSUE THREAD

**Issue by samstickland** [apotonick/reform#368]
Validating a second time with a form object does not clear the errors from the first run.

Take this simple form:

```
class MyForm < Reform::Form
  property :name
  validates :name, length: { maximum: 200}
end
```

Passing it a name of 201 characters, followed by a name of 200 characters still results in an false validation.

```
form = MyForm.new(OpenStruct.new)
form.validate(name: 'x' * 201)
=> false
form.validate(name: 'x' * 200)
=> false
form.errors[:name]
=> ["is too long (maximum is 200 characters)"]
```

**Comment by samstickland** [comment]
Well, this is a nasty hack, but adding the line with the comment below 'fixes' this:

```
module Reform::Contract::Validate
  def initialize(*)
    @errors = build_errors
    super
  end

  attr_reader :errors

  def validate
    @errors = build_errors # ADDED!
    validate!(errors, [])

    errors.empty?
  end
```

I tried moving the building of the errors from `initalize` to `validate` but bizarrely ActiveModel is already involved in trying to add errors to the errors object, and it bombs out like this:

```
     NoMethodError:
       undefined method `add' for nil:NilClass
     # /Users/samuelstickland/.rvm/gems/ruby-2.3.0/gems/reform-2.1.0/lib/reform/form/active_model/validations.rb:59:in `block in call'
     # /Users/samuelstickland/.rvm/gems/ruby-2.3.0/gems/activemodel-4.2.6/lib/active_model/errors.rb:164:in `block (2 levels) in each'
     # /Users/samuelstickland/.rvm/gems/ruby-2.3.0/gems/activemodel-4.2.6/lib/active_model/errors.rb:164:in `each'
     # /Users/samuelstickland/.rvm/gems/ruby-2.3.0/gems/activemodel-4.2.6/lib/active_model/errors.rb:164:in `block in each'
     # /Users/samuelstickland/.rvm/gems/ruby-2.3.0/gems/activemodel-4.2.6/lib/active_model/errors.rb:163:in `each_key'
     # /Users/samuelstickland/.rvm/gems/ruby-2.3.0/gems/activemodel-4.2.6/lib/active_model/errors.rb:163:in `each'
     # /Users/samuelstickland/.rvm/gems/ruby-2.3.0/gems/reform-2.1.0/lib/reform/form/active_model/validations.rb:58:in `call'
```

I'm happy to help fix this and submit a PR, but I could do with some guidance.

**Comment by samstickland** [comment]
Btw, I'm doing this so that it's possible to use the shoulda validation matchers against contracts like this:

```
       subject(:form) { Artist::Create.contract_class.new(Artist.new) }

        it { is_expected.to validate_presence_of(:name) }
        it { is_expected.to validate_length_of(:name).is_at_most(200) }

        context "when platinum" do
          before { form.platinum = true }

          it { is_expected.to validate_presence_of(:legal_type) }
        end
```

Some of the shoulda matchers (such as length) will call valid? on the subject multiple times.

**Comment by heeton** [comment]
@samstickland What's your use-case here? I've not come across a situation in my own code where the form isn't freshly instantiated.

**Comment by samstickland** [comment]
@heeton Only the one I mention in the final comment - the ActiveModel validation tests from shoulda-matchers run validation on the object multiple times.

Without clearing errors before each validation `validate_length_of` will fail for instance (because it first tests with a string that it expects to be too long, before testing again with a string of maximum length)

I can't honestly think of a situation where this might happen in production, but it's quite useful in testing.

**Comment by samstickland** [comment]
Also, tangentially related, I can't get the reform tests to run. Both master and tags/v2.1.0 fail with:

```
/Users/samuelstickland/development/reform/test/validation/dry_validation_test.rb:18:in `block in <class:SessionForm>': undefined method `key' for #<Class:0x007fe7e791c158> (NoMethodError)
	from /Users/samuelstickland/development/reform/lib/reform/form/dry.rb:28:in `class_eval'
	from /Users/samuelstickland/development/reform/lib/reform/form/dry.rb:28:in `instance_exec'
	from /Users/samuelstickland/development/reform/lib/reform/validation.rb:15:in `validation'
	from /Users/samuelstickland/development/reform/test/validation/dry_validation_test.rb:17:in `<class:SessionForm>'
```

I just did a straight `gem install dry-validation`. Is there a particular version required?

**Comment by heeton** [comment]
@samstickland Sorry, I think I missed out the word "production" :)

**Comment by samstickland** [comment]
@heeton Sure, I see what you are saying ;)

Although I am curious to know how people are testing Reform/Operation Contracts/dry-validation schemas. The tests in trailblazer book are reasonably long-winded:

```
  it "invalid description" do
    res, op = Thing::Create.run(thing: {name: "Rails", description: "hi"})

    res.must_equal false
    op.errors.to_s.must_equal "{:description=>[\"is too short (minimum is 4 characters)\"]}"
  end
```

**Comment by apotonick** [comment]
Reform's API is **not designed** to do `validate` more than once, and in Reform 3.0, the API won't allow this anymore.

**Comment by samstickland** [comment]
@apotonick Sure.

I have this PR open in shoulda-matchers https://github.com/thoughtbot/shoulda-matchers/pull/934 the upshot of this if that it will be modifed to do something like:

```
def perform_validation
  if record.is_a?(Reform::Form)
    record.errors.clear
    record.validate({})
  elsif context
    record.valid?(context)
  else
    record.valid?
  end
  ...
end
```

I don't know if calling `records.errors.clear` is "supported" in Reform + ActiveModel?

If it's not, then it's going to require a _very_ extensive rewrite of the shoulda-matchers to run these sort of validation tests against Reform / Contract.

And tbh, I'm not even sure if it even plays nicely with the testing frameworks to re-instantiate the object-under-test during the test :/

I really am having a hard-time trying to transition an active project from Rails to TrailBlazer, it seems like there's just too many pieces that need to change.

**Comment by apotonick** [comment]
If Shoulda doesn't provide a simple interface where we could re-instantiate (I think it exists), then we have to refactor Shoulda. It shouldn't be a big deal. They won't accept anything like `if Reform..`. :wink: 

Trailblazer is not Rails, and will never be. The whole point about it is to make people start to architect their software instead of blindly hacking thousands of code lines "the Rails Way". I'm sorry to hear you're struggling, but it doesn't make sense to simply add some more methods to ActiveRecord and then live the illusion of a better system design.

**Comment by samstickland** [comment]
Well I only proposed the if statement to demonstrate the functionality.
Their view on it was "So, in that new light, I think it would be acceptable
to hardcode a reference to Reform::Form for now, and then perhaps we can
revisit this when the change you mentioned gets into Reform."

But since reform won't support clearing of errors (even with ActiveModel
validations under the hood) that isn't going to fly.

2016-06-15 13:15 GMT+01:00 Nick Sutterer <notifications@github.com>:
