### ISSUE TITLE
Does Coercion work with ActiveModel validations?

### ISSUE THREAD

**Issue by yjukaku** [apotonick/reform#375]
I have a Form object that needs to use Coercion, but it looks like it can't find the Coercion constant:

module MyEngine
  class DocumentRequirementsForm < Reform::Form
    feature Coercion
    #... my props + validations
  end
end

Give back this error:

> `uninitialized constant MyEngine::DocumentRequirementsForm::Coercion`

Is Coercion not supported when using ActiveModel validations?

**Comment by apotonick** [comment]
```ruby
require "reform/form/coercion"
```

**Comment by yjukaku** [comment]
Thanks. I could have sworn this wasn't in the documentation when I checked 💭  😨
