### ISSUE TITLE
[Reform] Your :populator did not return a Reform::Form instance for model

### ISSUE THREAD

**Issue by kalashnikovisme** [apotonick/reform#376]
I have problem

```ruby
class Comment < ActiveRecord::Base
  has_one :document
end

class Document < ActiveRecord::Base
end
```

```ruby
class CommentForm < Refom::Form
  property :document, form: DocumentForm
end

class DocumentForm < Reform::Form
end
```

Error:

```
[Reform] Your :populator did not return a Reform::Form instance for `document`.
```

I explore your sources to know, what I do wrong. Any ideas?

**Comment by apotonick** [comment]
http://trailblazer.to/gems/reform/populator.html

**Comment by apotonick** [comment]
And come join the chat if you need more help: https://gitter.im/trailblazer/chat :beers:

**Comment by kalashnikovisme** [comment]
@apotonick I knew it. When I try to add any populator to my form, I have error:

`wrong number of arguments (given 2, expected 0..1)`

on line

```
@form.validate params[:comment]
```

**Comment by apotonick** [comment]
Then your populator code is wrong, paste your form, please.

**Comment by kalashnikovisme** [comment]
```ruby
class CommentForm < Reform::Form
  properties :some, :attributes

  property :document, form: DocumentForm, populate_if_empty: Document
end
```

I think, I don't understand something.

**Comment by apotonick** [comment]
That is correct code! Can you join the support chat, I can help you there better.

**Comment by kalashnikovisme** [comment]
@apotonick ок.

**Comment by kalashnikovisme** [comment]
thanks @fran-worley for help! Working code looks like this:

```ruby
class CommentForm < ApplicationForm
  properties :text, :user_id, :record_id, :record_type, :comment_type, :comment_date

  property :document, form: DocumentForm,
    populator: -> (model:, **) { model || self.document = Document.new }
end
```

```ruby
class DocumentForm < ApplicationForm
  properties :content, :record_id, :record_type
end
```
*app/controllers/comments_controller.rb*

```ruby
def new
  @comment_form = CommentForm.new Comment.new
  @comment.model.build_document
end

def create
  @comment_form = CommentForm.new Comment.new
  if @comment_form.validate params[:comment]
    if @comment.save
      #{...}
    end
  end
end
```

**Comment by fran-worley** [comment]
You don't need an if on save. If you've validated it you can just call save.

Also you should consider using a prepopulator to load your document instance in the new method. But glad it's working!



Sent from my iPhone

On 2 Jul 2016, at 21:12, ????? ?????????? <notifications@github.com<mailto:notifications@github.com>> wrote:


thanks @fran-worley<https://github.com/fran-worley> for help! Working code looks like this:

class CommentForm < ApplicationForm
  properties :text, :user_id, :record_id, :record_type, :comment_type, :comment_date

  property :document, form: DocumentForm,
    populator: -> (model:, **) { model || self.document = Document.new }
end

class DocumentForm < ApplicationForm
  properties :content, :record_id, :record_type
end

app/controllers/comments_controller.rb

def new
  @comment_form = CommentForm.new Comment.new
  @comment.model.build_document
end

def create
  @comment_form = CommentForm.new Comment.new
  if @comment_form.validate params[:comment]
    if @comment.save
      #{...}
    end
  end
end

-

**Comment by apotonick** [comment]
And consider introducing a `Trailblazer::Operation`, too, as this is the way to go. trailblazer.to/guides/trailblazer-in-20-minutes.html :beers:
