### ISSUE TITLE
Allow global configuration for dry-validation

### ISSUE THREAD

**Issue by gorkunov** [apotonick/reform#378]
Current dry-v version allows global configuration (useful for custom predicates and messages settings):
```ruby
Dry::Validation::Schema.configure do |config|
  config.messages = :i18n
  config.predicates = MyPredicates
end
```
Currently there is no way to handle this in reform and we need manually configure each `validation` block in form. 
It would be much useful to set this configuration only once in global reform config.

Related discussion https://github.com/apotonick/reform/pull/377

**Comment by fran-worley** [comment]
As of Reform 2.3 you will be able to either monkey patch reforms base schema (https://github.com/apotonick/reform/blob/master/lib/reform/form/dry.rb#L26) or pass your own into a validation block see this test for an example:
https://github.com/apotonick/reform/blob/master/test/validation/dry_validation_test.rb#L137

**Comment by siassaj** [comment]
Dry::Validation::Schema::Form.configure do |config|
  config.messages = :i18n
end

**Comment by fran-worley** [comment]
That is handy to know, I assumed you had to define a base class as per their docs:
http://dry-rb.org/gems/dry-validation/basics/working-with-schemas/

**Comment by siassaj** [comment]
wow. I just googled 'configure dry validations globally' and found my own answer ...

**Comment by siassaj** [comment]
wow. I just googled 'configure dry validations globally' and found my own answer ...

**Comment by micdahl** [comment]
@fran-worley (or someone else)
Could you please explain, how concrete to get i18n running? I have tried different methods which did not lead to a satisfying result (see [reform-rails issue](https://github.com/trailblazer/reform-rails/issues/57))
