### ISSUE TITLE
Issue with date field being blank

### ISSUE THREAD

**Issue by simonc** [apotonick/reform#38]
I have a date field in a a form and I check that the date is present.
When I submit the form I get a validation error saying that the date can't be blank.
Is it due to the way date fields are sent ?

app/controllers/legal_details_controller.rb

``` ruby
class LegalDetailsController < ApplicationController
  expose(:legal_details_form) do
    LegalDetailsForm.new(current_user)
  end

  def update
    if legal_details_form.validate(params[:legal_details])
      # ...
    end
  end
end
```

app/forms/legal_details_form.rb

``` ruby
class LegalDetailsForm < Reform::Form
  include Reform::Form::ActiveRecord

  properties %i[birthdate]

  model :legal_details

  validates :birthdate,
    presence: true
end
```

app/views/legal_details/edit.html.slim

``` haml
= simple_form_for legal_details_form, url: legal_details_path do |f|
  = f.input :birthdate, as: :date
  = f.button :button
```
_params_

    "legal_details" => {
      "birthdate(3i)" => "1",
      "birthdate(2i)" => "1",
      "birthdate(1i)" => "2013"
    }

**Comment by hydrozen** [comment]
I know this issue is old but what’s the proper way to handle those dates that are in 3 separate fields with reform?

**Comment by apotonick** [comment]
Sounds like a different issue, @hydrozen ? Can you be more specific about the three separate fields?

**Comment by hydrozen** [comment]
@apotonick I setup a simple reform class which has `property :date` and it validates its presence. But the form is using the default date select from rails so the params look like `"date(1i)"=>"2015", "date(2i)"=>"8", "date(3i)"=>"15"` and the validation then says that the date is missing.

**Comment by apotonick** [comment]
@hydrozen Here is where the multiparam "problem" is handled in Reform: https://github.com/apotonick/reform/blob/7657fd3177549cd91beae7753fb65b6cebaf2900/lib/reform/form/multi_parameter_attributes.rb#L40

As you can see, the `#deserialize!` method is meant to normalize data from your user-specific input to the Reform format.

Does the link to `MultiParameterAttributes` help? Any idea whether or not your fix is worth merging it into that module?

**Comment by hydrozen** [comment]
@apotonick but do I need to give reform some option to the property so that it knows to use `MultiParameterAttributes`?

**Comment by apotonick** [comment]
https://github.com/apotonick/reform#multiparameter-dates

**Comment by faucct** [comment]
@apotonick , the link in master branch README is dead

**Comment by apotonick** [comment]
http://trailblazer.to/gems/reform/#multiparameter-dates :grimacing:

**Comment by fran-worley** [comment]
Multi-parameter-attributes code has moved to the reform-rails gem. I'll be closing this here and if you're still having issues can you raise them in the new gem?

**Comment by scookdev** [comment]
Adding `, as: :date` to the input field did the trick for me on Rails 5.2.
