### ISSUE TITLE
DateTime validation with DateTime coercion

### ISSUE THREAD

**Issue by jakefolio** [apotonick/reform#380]
When I define a property with `DateTime` type and also a validation for `:date_time?` I receive an error in my specs.

```RUBY
property  :starts_at, type: Types::Form::DateTime

validation :default do
  required(:starts_at).filled(:date_time?)
end
```

I receive the following stack trace:
```
NoMethodError:
    undefined method `downcase' for Mon, 30 May 2016 00:00:00 +0000:DateTime
# timecop-0.8.1/lib/timecop/time_extensions.rb:101:in `parse_with_mock_date'
# dry-types-0.8.0/lib/dry/types/coercions.rb:17:in `to_date_time'
# dry-types-0.8.0/lib/dry/types/constructor.rb:33:in `[]'
# dry-types-0.8.0/lib/dry/types/constructor.rb:33:in `try'
# dry-types-0.8.0/lib/dry/types/safe.rb:16:in `try'
# dry-types-0.8.0/lib/dry/types/hash/schema.rb:85:in `block in call'
# dry-types-0.8.0/lib/dry/types/hash/schema.rb:83:in `each'
# dry-types-0.8.0/lib/dry/types/hash/schema.rb:83:in `each_with_object'
# dry-types-0.8.0/lib/dry/types/hash/schema.rb:83:in `call'
# dry-types-0.8.0/lib/dry/types/hash/schema.rb:24:in `try'
# dry-types-0.8.0/lib/dry/types/hash/schema.rb:73:in `try'
# dry-types-0.8.0/lib/dry/types/constructor.rb:33:in `try'
# dry-types-0.8.0/lib/dry/types/safe.rb:16:in `try'
# dry-types-0.8.0/lib/dry/types/safe.rb:11:in `call'
# dry-validation-0.8.0/lib/dry/validation/schema.rb:253:in `call'
# reform-2.2.1/lib/reform/form/dry.rb:38:in `call'
# reform-2.2.1/lib/reform/validation/groups.rb:57:in `block in call'
# reform-2.2.1/lib/reform/validation/groups.rb:51:in `each'
# reform-2.2.1/lib/reform/validation/groups.rb:51:in `call'
# reform-2.2.1/lib/reform/validation.rb:36:in `valid?'
# reform-2.2.1/lib/reform/contract/validate.rb:18:in `validate!'
# reform-2.2.1/lib/reform/contract/validate.rb:10:in `validate'
# reform-2.2.1/lib/reform/form/validate.rb:23:in `validate'
```

**Comment by fran-worley** [comment]
@jakefolio thanks for raising this. 

Can you try the fix on branch dry-v-coercion-issues for me and let me know if it's still broken? 
My test case using your example seems to be passing fine.

**Comment by NekoNova** [comment]
suffering from the same issue on the latest version.
Could it be related to timecop?

**Comment by fran-worley** [comment]
@NekoNova this issue is specifically related to Reform & Dry-v coercion issues. If your experiencing an issue with some other aspect you'll need to raise a new issue.

The fix I mentioned is still in branch and hasn't been merged yet. Please try and it let me know if it helps.

**Comment by NekoNova** [comment]
I'll test the branch locally tomorrow at work.
I cannot however use it until it's official released.
Not pulling in master/other branches outside official releases on our production ;)
Will post here tomorrow.

**Comment by NekoNova** [comment]
Okay,

I've tested the branch and it definitely fixes the coercion problem on the DateTime objects for our forms. However, Boolean virtual properties seem to be broken, as my validations on a form object now throw an ArgumentError: 

`Uncaught exception: wrong number of arguments (2 for 3)` and the only change made was adding the dry- stuff to it instead of the old Axiom types.

**Comment by fran-worley** [comment]
Thanks for letting me know, can you post your dry- stuff ?

**Comment by NekoNova** [comment]
We basically have a form that more or less looks like this:

```
 module ReFormObjects
   module Admins
     class Customer < ::ReFormObjects::Admins::Base
       model :customer
       property :fill_with_demo_data, virtual: true, type: Types::Form::Bool
    end
  end
end
```

the base form basically adds:
```
    include Coercion
    include Reform::Form::ActiveModel::ModelReflections
```
and some properties, nothing more. Nothing that got changed anyway.
And when running specs, I get that argument error when calling `.validate` on my form object with passing in the parameters.

**Comment by fran-worley** [comment]
@NekoNova I've added a test to cover boolean coercion (https://github.com/apotonick/reform/commit/dd485170e262064024b05138f9b5ed9f02ff5df3) on this branch and it passes. I've checked it with both virtual and non virtual and it makes no difference.

Could you post your stack trace?

**Comment by NekoNova** [comment]
I'll have to ask, cause we normally don't share production code.

**Comment by fran-worley** [comment]
@NekoNova don't worry about it then. This branch resolves the date time coercion issue I suspect that your issue is a result of changing dry-validation versions rather than the changes in this branch. 

If you are still having issues please raise another issue, but I'll need a bit more of the stack trace to see where the error is being triggered from.

**Comment by pvmeerbe** [comment]
FYI I posted an issue/pull request on timecop as I think the the '.downcase' call done by timecop is incorrect (see https://github.com/travisjeffery/timecop/issues/188 )
