### ISSUE TITLE
Rails 4 - is it ready?

### ISSUE THREAD

**Issue by danielkummer** [apotonick/reform#39]
I'm asking because I'd like to use the gem in a new Rails 4 project.

My first attempts are unsuccessful - I'm getting an "undefined method `persisted?'" error...

**Comment by agm1988** [comment]
NoMethodError (undefined method `persisted?'
also having this issue
added 
require 'trailblazer/rails/railtie'
require 'reform/rails'
in config/application.rb

**Comment by fran-worley** [comment]
@agm1988 you'll need to open a new issue for this but before you do please check that you're using reform-rails as we moved methods like 'persisted?' out of Reform core.
