### ISSUE TITLE
Using `validation do … end` in a contract (via Trailblazer) issues a warning at startup

### ISSUE THREAD

**Issue by contentfree** [apotonick/reform#395]
### Complete Description of Issue

Given an Operation similar to:
```ruby
class MyOperation < Trailblazer::Operation
  validation do
    # ...
  end
end
```
At application startup, a warning will be printed:
`[Reform] Form::validation API is now: validation(name: :default, if:nil, schema:Schema). Please use keyword arguments instead of positional arguments.`

Not sure what's triggering this message since I'm not obviously providing an arguments whatsoever.

### System configuration
**Reform version**: master@777ea47

**Comment by fran-worley** [comment]
Thanks @contentfree I've just fixed this via https://github.com/apotonick/reform/commit/d6963bb4e5f13c488ea396f99adfa0d64a4bd4ff

**Comment by contentfree** [comment]
💯 🎉 @fran-worley
