### ISSUE TITLE
Reform model inaccessible when used with Dry Validation

### ISSUE THREAD

**Issue by nhippenmeyer** [apotonick/reform#396]
When instantiating the following QuestionForm as follows: `QuestionForm.new(question)`, the form object is nil and the question model is inaccessible from within the validation block.  Any insight into how to make it accessible?

```ruby
class QuestionForm < Reform::Form
  require 'reform/form/dry'

  feature Reform::Form::Dry

  property :question_identifier, virtual: true
  property :user_responses, virtual: true

  validation :default do
    configure do
      option :form
      config.messages_file = 'lib/validation/reform_messages.yml'

      def response_values
        form.model.response_values
      end
    end
    required(:user_responses).filled(included_in?: response_values)
  end
end
```

**Comment by fran-worley** [comment]
Couple of things:
1) what version of dry-validation are you using
2) when you run form.validate(params) does it error and where?

**Comment by fran-worley** [comment]
See https://github.com/dry-rb/dry-validation/issues/232 for the dry-validation issue that relates to this and even better, this feature has been added via https://github.com/apotonick/reform/pull/388/commits/c30d9245287eb34ccf27f6ee06f8ae62fd4f45d6 which will be included in the 2.3.0 release of reform.

**Comment by coding-test-reviewer-fdf7ba3** [comment]
@fran-worley Nice!

**Comment by ZimbiX** [comment]
@fran-worley Nice!
