### ISSUE TITLE
Feels confused about prepopulator uses

### ISSUE THREAD

**Issue by nicolas-besnard** [apotonick/reform#407]
I've been playing with Reform for a while now, and I don't really understand why I can't give a form to the `prepopulator` options.

Given the form:

```ruby
class AlbumForm < Reform::Form
  property :artist, prepopulator: ->(options) { self.artist = Artist.new } do
    property :name
  end
```

What if the artist property has a lot of nested property and validation ? I've seen that the property have a `form` option, but this doesn't seems to work.

I've been stuck with this problem for the past 2 hours, I'll be happy to show you my test if you need it.

**Comment by fran-worley** [comment]
i think you might be getting confused between prepopulators and populators. Prepopulators have to be manually called and are used purely for rendering purposes. Whereas populators are called prior to validation automatically.

To call your prepopulator you need to use the prepopulator!(options) method on your form instance.

For more information checkout the reform documentation on the trailblazer site (trailblazer.to) or checkout the trailblazer gitter room for a community full of support. 

Unless you've got an error I'm going to close this as the issue tracker is just for bug reports, but do checkout the gitter group for more help.
