### ISSUE TITLE
error after upgrade

### ISSUE THREAD

**Issue by thirumal1** [apotonick/reform#409]
Hi,
Here is the issues I am having after migration. Please Advise

Complete Description of Issue : After migration to Rails 4.2.7.1 I am receiving below error

Steps to reproduce : Got this error when executing rake task
bundle exec rake assets:clobber

### System configuration
**Reform version**:reform (1.0.3)

### Full Backtrace of Exception (if any)
[arwins_app@tanf-devap arwins_tanf_app]$ RAILS_ENV=production bundle exec rake assets:clobber
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'reform'.
Gem Load Error is: wrong number of arguments (given 2, expected 1)
Backtrace for gem load error is:
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/forwardable.rb:133:in `instance_delegate'
/usr/local/rvm/gems/ruby-2.3.1/gems/activemodel-4.2.7.1/lib/active_model/naming.rb:220:in `extended'
/usr/local/rvm/gems/ruby-2.3.1/gems/activemodel-4.2.7.1/lib/active_model/validations.rb:42:in `extend'
/usr/local/rvm/gems/ruby-2.3.1/gems/activemodel-4.2.7.1/lib/active_model/validations.rb:42:in `block in <module:Validations>'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/concern.rb:120:in `class_eval'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/concern.rb:120:in `append_features'
/usr/local/rvm/gems/ruby-2.3.1/gems/reform-1.0.3/lib/reform/contract.rb:79:in `include'
/usr/local/rvm/gems/ruby-2.3.1/gems/reform-1.0.3/lib/reform/contract.rb:79:in `<class:Contract>'
/usr/local/rvm/gems/ruby-2.3.1/gems/reform-1.0.3/lib/reform/contract.rb:8:in `<module:Reform>'
/usr/local/rvm/gems/ruby-2.3.1/gems/reform-1.0.3/lib/reform/contract.rb:6:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/reform-1.0.3/lib/reform/form.rb:3:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/reform-1.0.3/lib/reform/form.rb:3:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/reform-1.0.3/lib/reform.rb:9:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/reform-1.0.3/lib/reform.rb:9:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `block in require'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler.rb:106:in `require'
/var/www/webapps/arwins_tanf_app/config/application.rb:7:in `<top (required)>'
/var/www/webapps/arwins_tanf_app/Rakefile:4:in `require'
/var/www/webapps/arwins_tanf_app/Rakefile:4:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/rake-11.3.0/lib/rake/rake_module.rb:28:in `load'
/usr/local/rvm/gems/ruby-2.3.1/gems/rake-11.3.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/usr/local/rvm/gems/ruby-2.3.1/gems/rake-11.3.0/lib/rake/application.rb:686:in `raw_load_rakefile'
/usr/local/rvm/gems/ruby-2.3.1/gems/rake-11.3.0/lib/rake/application.rb:96:in `block in load_rakefile'
/usr/local/rvm/gems/ruby-2.3.1/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.3.1/gems/rake-11.3.0/lib/rake/application.rb:95:in `load_rakefile'
/usr/local/rvm/gems/ruby-2.3.1/gems/rake-11.3.0/lib/rake/application.rb:79:in `block in run'
/usr/local/rvm/gems/ruby-2.3.1/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.3.1/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/usr/local/rvm/gems/ruby-2.3.1/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.3.1/bin/rake:23:in `<main>'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Bundler Error Backtrace:
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:90:in `block (2 levels) in require'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `block in require'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler.rb:106:in `require'
/var/www/webapps/arwins_tanf_app/config/application.rb:7:in `<top (required)>'
/var/www/webapps/arwins_tanf_app/Rakefile:4:in `require'
/var/www/webapps/arwins_tanf_app/Rakefile:4:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
ArgumentError: wrong number of arguments (given 2, expected 1)
/usr/local/rvm/gems/ruby-2.3.1/gems/activemodel-4.2.7.1/lib/active_model/naming.rb:220:in `extended'
/usr/local/rvm/gems/ruby-2.3.1/gems/activemodel-4.2.7.1/lib/active_model/validations.rb:42:in `extend'
/usr/local/rvm/gems/ruby-2.3.1/gems/activemodel-4.2.7.1/lib/active_model/validations.rb:42:in `block in <module:Validations>'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/concern.rb:120:in `class_eval'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/concern.rb:120:in `append_features'
/usr/local/rvm/gems/ruby-2.3.1/gems/reform-1.0.3/lib/reform/contract.rb:79:in `include'
/usr/local/rvm/gems/ruby-2.3.1/gems/reform-1.0.3/lib/reform/contract.rb:79:in `<class:Contract>'
/usr/local/rvm/gems/ruby-2.3.1/gems/reform-1.0.3/lib/reform/contract.rb:8:in `<module:Reform>'
/usr/local/rvm/gems/ruby-2.3.1/gems/reform-1.0.3/lib/reform/contract.rb:6:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/reform-1.0.3/lib/reform/form.rb:3:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/reform-1.0.3/lib/reform/form.rb:3:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/reform-1.0.3/lib/reform.rb:9:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/reform-1.0.3/lib/reform.rb:9:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `block in require'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler.rb:106:in `require'
/var/www/webapps/arwins_tanf_app/config/application.rb:7:in `<top (required)>'
/var/www/webapps/arwins_tanf_app/Rakefile:4:in `require'
/var/www/webapps/arwins_tanf_app/Rakefile:4:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

Thanks in advance 

Rao

**Comment by fran-worley** [comment]
Thanks for getting in touch. 

You'll need to upgrade reform to at least 2.1.0, if you need any help with that process or need advice, checkout the guys on the Gitter channel.

**Comment by thirumal1** [comment]
I got it resolved.
Thanks for your advise.
RegardsRao
