### ISSUE TITLE
validate :on currently not working

### ISSUE THREAD

**Issue by cj** [apotonick/reform#57]
http://edgeguides.rubyonrails.org/active_record_validations.html#on Is currently not working, reform ignores it.

A current work around if anyone else has the issue:

```ruby
validates :some_column, presence: true, if: ->(f) { f.model.new_record? }
```

**Comment by fran-worley** [comment]
This has gone a little stale. I think that this is somewhat mitigated when a form is encapsulated within an operation. 

If using dry-validations you could also build rules that only run if your form is persisted e.g.

```ruby
def valid_field(value)
  return true if !form.persisted?  # the check passes
  
  value > 12 # if persisted then we check further
end
```

I'm going to close this, but please reopen if you need. 😄
