### ISSUE TITLE
Virtual Attributes for Compositions

### ISSUE THREAD

**Issue by niedhui** [apotonick/reform#75]
Hi, I saw reform support Virtual Attributes now,  a really helpful feature,but it seems not working with compositions, I tried to make it work, since I'm not good at writting test, and not known reform's code structure very well, please help me review what I'm done,
https://github.com/niedhui/reform/commit/4b15ec12b9925fd8d6ca7de62e00a6d997be6ab7    thanks

**Comment by pdobb** [comment]
Argh. Thank you. I had no idea about the `reform_2_0!` method and virtual properties were not working without it (even when not using composition).
