### ISSUE TITLE
Wizard-style forms

### ISSUE THREAD

**Issue by emptyflask** [apotonick/reform#85]
I'd like to use Reform to build a wizard / multi-step form that validates on each step, but also when the entire process is complete -- the final submission should repeat validations from all previous steps.

I could repeat properties and validations in the final step class, but is there a way I can simply inherit from a group of other forms?

e.g.:
```ruby
class StepOne < Reform::Form
  property :name
  validates :name, presence: true
end

class StepTwo < Reform::Form
  property :email
  validates :email, presence: true
end

class Finalize < Reform::Form
  # this of course does not work
  include StepOne
  include StepTwo
end
```

**Comment by fran-worley** [comment]
As this will be reaching the 2 year anniversary of the last comment and @kirel no longer has access to the code that inspired the issue I'm going to close this. Feel free to reopen if you think we need to revisit.
