### ISSUE TITLE
save: false on collection appears to still save associated models

### ISSUE THREAD

**Issue by bradrobertson** [apotonick/reform#89]
Check out [this repository](https://github.com/bradrobertson/reform_auto_save/commit/277b871328e146d598111b431927909049f399b5)

You can see in `app/forms/author_book_form.rb` I've got a collection of books on an author with `save: false` specified.

Check out the failing test at `test/forms/author_book_form_test.rb`. If you build an author, and 2 books, throw it in a form and call `save`. The books are in fact persisted.

Unless I'm missing something, it seems according to [the docs](https://github.com/apotonick/reform#turning-off-autosave) that this should _not_ be the case.

**Comment by apotonick** [comment]
This is now fixed in Reform 2.0 just as I described it a year ago.

Collections will only be saved when calling `Form#sync` as this will call `model.songs = []`.
